import { NextRequest, NextResponse } from "next/server";

const WEBSITE_CONTEXT = `You are LinkBot, LoadLink's friendly AI help assistant for a South African logistics marketplace. Help users use LoadLink naturally and conversationally. You can explain accounts, login, verification, jobs, contracts, trucks, trailers, mobile toilets, mobile fridges, food trucks, mobile kitchens, search, saving, sharing, reporting, private messaging, the 50-message standard allowance, Pro messaging, analytics, listing photos, rates in rand, safety, missing listings, page navigation and technical troubleshooting. Ask one short clarifying question when needed. Give direct step-by-step help and suggest the correct LoadLink page. Never invent a user's account, listing, payment or verification status. Never provide general unrelated advice. When a user needs a person, say that agent support is being connected and ask them to prepare their account email, listing link and a short problem description.`;

type Faq={keys:string[];answer:string;followups:string[]};
const faq:Faq[]=[
 {keys:["agent","human","person","support","complaint"],answer:"I can help first, or you can speak to an agent. For the fastest handover, keep your account email, the listing link and a short description of what went wrong ready.",followups:["Keep helping me","Talk to an agent"]},
 {keys:["verify","verification","id","passport","otp","badge"],answer:"Open Account Verification, confirm your South African cellphone number, then upload your ID or passport and a clear selfie. Your documents stay private. The gold badge appears only after approval.",followups:["Why is my OTP not arriving?","Check verification status","Talk to an agent"]},
 {keys:["otp","sms","code"],answer:"Check that the number starts with +27, wait a minute, then request one new code. Do not request several codes quickly. If no SMS arrives, the site owner should confirm that the Supabase SMS provider is active.",followups:["Try verification again","Talk to an agent"]},
 {keys:["post job","list job","create job","need vehicle"],answer:"Open the Jobs portal and choose List a job. Use a specific title, select what vehicle or mobile unit is needed, add the exact location, rate, dates, description and contact method, then upload a clear cover photo.",followups:["What makes a good title?","What can I request?","How do rates work?"]},
 {keys:["contract","post contract"],answer:"Use the Contracts portal and choose Post a contract. Include the route or work area, contract duration, load or service, required vehicle, frequency, rate or tender terms and the decision deadline.",followups:["Find contracts","Contract safety checks","Talk to an agent"]},
 {keys:["truck","trailer","mobile toilet","mobile fridge","food truck","mobile kitchen","asset"],answer:"LoadLink supports trucks, trailers and relevant mobile units such as mobile toilets, fridges, food trucks and mobile kitchens. Choose List a vehicle or mobile unit from the plus menu and select the closest category.",followups:["List a vehicle","How many photos?","How do customers contact me?"]},
 {keys:["search","find","results","filter"],answer:"Search with the main details together, for example “side tipper job in Rustenburg” or “mobile fridge Johannesburg event”. LoadLink checks listing titles, categories, locations, descriptions and portal types while you type.",followups:["No results appear","Clear filters","Browse jobs"]},
 {keys:["missing","friends post","not showing","disappear"],answer:"Open the correct portal, clear every filter and search using the exact title or poster name. If the listing still does not appear, ask the poster whether submission completed and send the title to support.",followups:["Clear filters","Refresh listings","Talk to an agent"]},
 {keys:["price","rate","currency","rand","r "] ,answer:"LoadLink displays listing prices in South African rand by default. Enter the amount and period clearly, such as R1 850 per day, R12 000 per trip or Negotiable.",followups:["Edit my rate","Why show a rate?","Create a listing"]},
 {keys:["message","chat","typing","last seen","50"],answer:"Use Message on a listing to start a private LoadLink conversation with that poster. Standard accounts can send 50 messages per day and see the remaining count. Chats keep their history, support files and show typing and last-seen status.",followups:["Why can’t I message?","Upload a file","Call the poster"]},
 {keys:["analytics","views","viewer","graph","algorithm"],answer:"Public view totals remain on listings. Detailed graphs, traffic sources, device breakdowns and signed-in viewer details are Pro analytics features for the listing owner.",followups:["Improve listing visibility","What counts as a view?","View Pro options"]},
 {keys:["pro","premium","promoted","featured"],answer:"Pro adds advanced analytics and unlimited messaging. Promoted placement can also put a listing in the featured rail for its portal. Accurate information and a strong cover photo still matter most.",followups:["Pro analytics","Featured listings","Standard account limits"]},
 {keys:["photo","image","cover"],answer:"Use recent, accurate photos with the strongest image first. Show the full truck, trailer or mobile unit, then add useful interior, equipment and condition photos. Avoid unrelated stock photos on listings.",followups:["How many photos?","Change cover photo","Create a listing"]},
 {keys:["report","scam","fake","fraud","unsafe"],answer:"Tap Report on the listing and explain what happened. Do not send OTP codes, passwords, banking PINs or identity documents to another user. Confirm the person, company, route, cargo, rate and payment terms before work starts.",followups:["Report a listing","Safety checklist","Talk to an agent"]},
 {keys:["login","sign in","password","account"],answer:"Use the account icon to open Login. For a forgotten password, choose Forgot password and follow the reset email. If the email is delayed, check spam and confirm the address is correct.",followups:["Forgot password","Create an account","Talk to an agent"]},
 {keys:["save","liked","favourite"],answer:"Tap Save on a listing. You can return to saved listings from the Liked section in Recent Activity.",followups:["Open saved listings","Why is a saved listing gone?"]},
 {keys:["android","iphone","computer","desktop","crash","404","bug"],answer:"Refresh once, return to the homepage and reopen the portal. Keep the browser updated and disable private browsing if login state is not being saved. For a 404, send support the exact page link and device type.",followups:["Page still won’t open","Missing listing","Talk to an agent"]},
];
function fallback(message:string){const words=message.toLowerCase();let best:Faq|undefined;let score=0;for(const item of faq){const current=item.keys.reduce((n,key)=>n+(words.includes(key)?key.length:0),0);if(current>score){score=current;best=item}}return best||{answer:"Tell me what you are trying to do on LoadLink, what page you are on and what you expected to happen. I can guide you through it step by step.",followups:["Find a listing","Post a listing","Fix a problem","Talk to an agent"]};}

export async function POST(request:NextRequest){
 const body=await request.json().catch(()=>({})); const message=String(body?.message||"").trim().slice(0,1200); const history=Array.isArray(body?.history)?body.history.slice(-8):[];
 if(!message)return NextResponse.json({answer:"Ask me anything about using LoadLink.",followups:["Find a listing","Post a listing","Talk to an agent"]},{status:400});
 const key=process.env.OPENAI_API_KEY;
 if(key){try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_LINKBOT_MODEL||"gpt-5-mini",instructions:WEBSITE_CONTEXT,input:[...history.map((m:any)=>({role:m.from==="bot"?"assistant":"user",content:String(m.text||"")})),{role:"user",content:message}],max_output_tokens:320}),signal:AbortSignal.timeout(14000)});if(response.ok){const data=await response.json();const answer=data.output_text||data.output?.flatMap((i:any)=>i.content||[]).map((p:any)=>p.text||"").join(" ");if(answer)return NextResponse.json({answer,followups:["Ask another question","Talk to an agent"],ai:true})}}catch{}}
 const result=fallback(message);return NextResponse.json({...result,ai:false});
}
