-- LoadLink messaging, 50-message allowance, private attachments,
-- listing-view tracking, and Pro listing analytics.
-- Run this ONCE in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. REQUIRED PROFILE AND LISTING COLUMNS
-- -----------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  subscription_plan text not null default 'standard',
  last_seen timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists full_name text,
  add column if not exists phone text,
  add column if not exists subscription_plan text not null default 'standard',
  add column if not exists last_seen timestamptz default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.profiles
set subscription_plan = 'standard'
where subscription_plan is null
   or subscription_plan not in ('standard', 'pro');

create table if not exists public.job_listings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  vehicle_group text not null,
  rate text not null,
  posted_by text not null,
  contact_number text not null default '',
  whatsapp_number text not null default '',
  poster_photo text not null default '',
  description text not null,
  photos text[] not null default '{}',
  sponsored boolean not null default false,
  package_type text not null default 'standard',
  owner_key text not null default '',
  user_id uuid references auth.users(id) on delete set null,
  view_count integer not null default 0,
  last_viewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.job_listings
  add column if not exists whatsapp_number text not null default '',
  add column if not exists poster_photo text not null default '',
  add column if not exists sponsored boolean not null default false,
  add column if not exists package_type text not null default 'standard',
  add column if not exists owner_key text not null default '',
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists view_count integer not null default 0,
  add column if not exists last_viewed_at timestamptz;

-- -----------------------------------------------------------------------------
-- 2. PRIVATE LISTING VIEW EVENTS
-- -----------------------------------------------------------------------------

create table if not exists public.job_view_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.job_listings(id) on delete cascade,
  viewer_hash text,
  viewer_user_id uuid references auth.users(id) on delete set null,
  device_type text not null default 'unknown',
  source text not null default 'direct',
  viewed_at timestamptz not null default now()
);

alter table public.job_view_events
  add column if not exists viewer_hash text,
  add column if not exists viewer_user_id uuid references auth.users(id) on delete set null,
  add column if not exists device_type text not null default 'unknown',
  add column if not exists source text not null default 'direct',
  add column if not exists viewed_at timestamptz not null default now();

-- Preserve data if an older version used a column called viewer_key.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'job_view_events'
      and column_name = 'viewer_key'
  ) then
    execute $sql$
      update public.job_view_events
      set viewer_hash = encode(digest(viewer_key, 'sha256'), 'hex')
      where viewer_hash is null
        and viewer_key is not null
    $sql$;
  end if;
end $$;

create index if not exists job_view_events_job_time_idx
  on public.job_view_events (job_id, viewed_at desc);

create index if not exists job_view_events_viewer_idx
  on public.job_view_events (job_id, viewer_hash);

alter table public.job_view_events enable row level security;

drop policy if exists "no_direct_view_event_access" on public.job_view_events;
create policy "no_direct_view_event_access"
on public.job_view_events
for all
to public
using (false)
with check (false);

-- Drop first because an older version may have used a different return type.
drop function if exists public.record_job_view(uuid, text, text, text);

create function public.record_job_view(
  p_job_id uuid,
  p_viewer_key text,
  p_device_type text default 'unknown',
  p_source text default 'direct'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_owner_key text;
  v_owner_user_id uuid;
  v_viewer_hash text;
  v_already_recorded boolean;
begin
  select owner_key, user_id
  into v_owner_key, v_owner_user_id
  from public.job_listings
  where id = p_job_id;

  if not found then
    return false;
  end if;

  if length(coalesce(p_viewer_key, '')) < 8 then
    return false;
  end if;

  -- Do not count the listing owner viewing their own listing.
  if coalesce(v_owner_key, '') = p_viewer_key
     or (auth.uid() is not null and auth.uid() = v_owner_user_id) then
    return false;
  end if;

  v_viewer_hash := encode(digest(p_viewer_key, 'sha256'), 'hex');

  select exists (
    select 1
    from public.job_view_events
    where job_id = p_job_id
      and viewer_hash = v_viewer_hash
      and viewed_at > now() - interval '30 minutes'
  )
  into v_already_recorded;

  if v_already_recorded then
    return false;
  end if;

  insert into public.job_view_events (
    job_id,
    viewer_hash,
    viewer_user_id,
    device_type,
    source,
    viewed_at
  )
  values (
    p_job_id,
    v_viewer_hash,
    auth.uid(),
    case
      when p_device_type in ('mobile', 'tablet', 'desktop') then p_device_type
      else 'unknown'
    end,
    case
      when p_source in ('direct', 'google', 'social', 'whatsapp', 'loadlink', 'referral') then p_source
      else 'other'
    end,
    now()
  );

  update public.job_listings
  set view_count = coalesce(view_count, 0) + 1,
      last_viewed_at = now()
  where id = p_job_id;

  return true;
end;
$$;

revoke all on function public.record_job_view(uuid, text, text, text) from public;
grant execute on function public.record_job_view(uuid, text, text, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 3. PRO LISTING ANALYTICS
-- -----------------------------------------------------------------------------

drop function if exists public.get_pro_job_analytics(uuid, text);

create function public.get_pro_job_analytics(
  p_job_id uuid,
  p_owner_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_job public.job_listings%rowtype;
  v_authorised boolean;
  v_result jsonb;
begin
  select *
  into v_job
  from public.job_listings
  where id = p_job_id;

  if not found then
    raise exception 'Listing not found';
  end if;

  if coalesce(v_job.package_type, 'standard') <> 'pro' then
    raise exception 'Pro analytics required';
  end if;

  v_authorised := (
    length(coalesce(p_owner_key, '')) > 20
    and coalesce(v_job.owner_key, '') = p_owner_key
  ) or (
    auth.uid() is not null
    and v_job.user_id = auth.uid()
  );

  if not v_authorised then
    raise exception 'Not authorised';
  end if;

  select jsonb_build_object(
    'total_views', coalesce(v_job.view_count, 0),
    'unique_viewers', (
      select count(distinct viewer_hash)
      from public.job_view_events
      where job_id = p_job_id
        and viewer_hash is not null
    ),
    'last_viewed_at', v_job.last_viewed_at,
    'daily_views', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'label', to_char(day_local, 'Dy'),
            'count', view_total
          )
          order by day_local
        ),
        '[]'::jsonb
      )
      from (
        select
          day_local,
          (
            select count(*)
            from public.job_view_events e
            where e.job_id = p_job_id
              and e.viewed_at >= (day_local at time zone 'Africa/Johannesburg')
              and e.viewed_at < ((day_local + interval '1 day') at time zone 'Africa/Johannesburg')
          ) as view_total
        from generate_series(
          date_trunc('day', now() at time zone 'Africa/Johannesburg') - interval '6 days',
          date_trunc('day', now() at time zone 'Africa/Johannesburg'),
          interval '1 day'
        ) as days(day_local)
      ) daily
    ),
    'devices', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object('label', device_type, 'count', total)
          order by total desc
        ),
        '[]'::jsonb
      )
      from (
        select coalesce(device_type, 'unknown') as device_type, count(*) as total
        from public.job_view_events
        where job_id = p_job_id
        group by coalesce(device_type, 'unknown')
      ) grouped_devices
    ),
    'sources', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object('label', source, 'count', total)
          order by total desc
        ),
        '[]'::jsonb
      )
      from (
        select coalesce(source, 'direct') as source, count(*) as total
        from public.job_view_events
        where job_id = p_job_id
        group by coalesce(source, 'direct')
      ) grouped_sources
    ),
    'recent_viewers', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'name', coalesce(nullif(trim(p.full_name), ''), 'LoadLink member'),
            'viewed_at', recent.viewed_at
          )
          order by recent.viewed_at desc
        ),
        '[]'::jsonb
      )
      from (
        select viewer_user_id, max(viewed_at) as viewed_at
        from public.job_view_events
        where job_id = p_job_id
          and viewer_user_id is not null
        group by viewer_user_id
        order by max(viewed_at) desc
        limit 12
      ) recent
      left join public.profiles p on p.id = recent.viewer_user_id
    )
  )
  into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_pro_job_analytics(uuid, text) from public;
grant execute on function public.get_pro_job_analytics(uuid, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 4. PRIVATE LOADLINK MESSAGING
-- -----------------------------------------------------------------------------

create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.job_listings(id) on delete set null,
  listing_title text not null default 'LoadLink listing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_participants (
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'LoadLink user',
  phone text,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  file_path text,
  file_name text,
  file_type text,
  created_at timestamptz not null default now(),
  check (char_length(body) <= 4000)
);

alter table public.chat_conversations
  add column if not exists listing_id uuid references public.job_listings(id) on delete set null,
  add column if not exists listing_title text not null default 'LoadLink listing',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.chat_participants
  add column if not exists display_name text not null default 'LoadLink user',
  add column if not exists phone text,
  add column if not exists joined_at timestamptz not null default now(),
  add column if not exists last_read_at timestamptz not null default now();

alter table public.chat_messages
  add column if not exists body text not null default '',
  add column if not exists file_path text,
  add column if not exists file_name text,
  add column if not exists file_type text,
  add column if not exists created_at timestamptz not null default now();

-- Remove accidental duplicate participant rows from earlier test migrations,
-- then enforce one participant record per conversation and user.
delete from public.chat_participants older
using public.chat_participants newer
where older.conversation_id = newer.conversation_id
  and older.user_id = newer.user_id
  and older.ctid < newer.ctid;

create unique index if not exists chat_participants_conversation_user_uidx
  on public.chat_participants (conversation_id, user_id);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at);

create index if not exists chat_messages_sender_created_idx
  on public.chat_messages (sender_id, created_at);

alter table public.chat_conversations enable row level security;
alter table public.chat_participants enable row level security;
alter table public.chat_messages enable row level security;

-- Remove policies first so the helper functions can be safely replaced on reruns.
drop policy if exists "participants read conversations" on public.chat_conversations;
drop policy if exists "participants read participants" on public.chat_participants;
drop policy if exists "participants read messages" on public.chat_messages;
drop policy if exists "chat participants upload files" on storage.objects;
drop policy if exists "chat participants read files" on storage.objects;

create or replace function public.is_chat_participant(p_conversation uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.chat_participants
    where conversation_id = p_conversation
      and user_id = auth.uid()
  );
$$;

revoke all on function public.is_chat_participant(uuid) from public;
grant execute on function public.is_chat_participant(uuid) to authenticated;

create or replace function public.is_chat_participant_text(p_conversation text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.chat_participants
    where conversation_id::text = p_conversation
      and user_id = auth.uid()
  );
$$;

revoke all on function public.is_chat_participant_text(text) from public;
grant execute on function public.is_chat_participant_text(text) to authenticated;

create policy "participants read conversations"
on public.chat_conversations
for select
to authenticated
using (public.is_chat_participant(id));

create policy "participants read participants"
on public.chat_participants
for select
to authenticated
using (public.is_chat_participant(conversation_id));

create policy "participants read messages"
on public.chat_messages
for select
to authenticated
using (public.is_chat_participant(conversation_id));

-- No direct insert/update/delete policies are created.
-- Messages and participants are written only through the protected functions below.

grant select on public.chat_conversations to authenticated;
grant select on public.chat_participants to authenticated;
grant select on public.chat_messages to authenticated;

-- -----------------------------------------------------------------------------
-- 5. PRIVATE CHAT ATTACHMENTS
-- -----------------------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'chat-attachments',
  'chat-attachments',
  false,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id)
do update set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "chat participants upload files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'chat-attachments'
  and public.is_chat_participant_text((storage.foldername(name))[1])
  and (storage.foldername(name))[2] = auth.uid()::text
);

create policy "chat participants read files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'chat-attachments'
  and public.is_chat_participant_text((storage.foldername(name))[1])
);

-- -----------------------------------------------------------------------------
-- 6. CHAT FUNCTIONS
-- -----------------------------------------------------------------------------

drop function if exists public.start_listing_conversation(uuid, uuid, text);

create function public.start_listing_conversation(
  p_listing_id uuid,
  p_other_user uuid,
  p_other_name text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_conversation_id uuid;
  v_listing_title text;
  v_listing_owner uuid;
  v_listing_phone text;
  v_me_name text;
  v_me_phone text;
  v_other_name text;
  v_other_phone text;
begin
  if auth.uid() is null then
    raise exception 'Sign in required';
  end if;

  select
    title,
    user_id,
    contact_number
  into
    v_listing_title,
    v_listing_owner,
    v_listing_phone
  from public.job_listings
  where id = p_listing_id;

  if not found then
    raise exception 'Listing not found';
  end if;

  if v_listing_owner is null then
    raise exception 'This listing is not connected to a LoadLink messaging account';
  end if;

  if p_other_user is distinct from v_listing_owner then
    raise exception 'Invalid recipient';
  end if;

  if v_listing_owner = auth.uid() then
    raise exception 'You cannot start a conversation with yourself';
  end if;

  select c.id
  into v_conversation_id
  from public.chat_conversations c
  join public.chat_participants me
    on me.conversation_id = c.id
   and me.user_id = auth.uid()
  join public.chat_participants other_person
    on other_person.conversation_id = c.id
   and other_person.user_id = v_listing_owner
  where c.listing_id = p_listing_id
  limit 1;

  if v_conversation_id is null then
    insert into public.chat_conversations (listing_id, listing_title)
    values (p_listing_id, coalesce(v_listing_title, 'LoadLink listing'))
    returning id into v_conversation_id;

    select
      coalesce(nullif(trim(full_name), ''), 'LoadLink user'),
      phone
    into v_me_name, v_me_phone
    from public.profiles
    where id = auth.uid();

    select
      coalesce(nullif(trim(full_name), ''), nullif(trim(p_other_name), ''), 'LoadLink user'),
      coalesce(phone, v_listing_phone)
    into v_other_name, v_other_phone
    from public.profiles
    where id = v_listing_owner;

    v_me_name := coalesce(v_me_name, 'LoadLink user');
    v_other_name := coalesce(v_other_name, nullif(trim(p_other_name), ''), 'LoadLink user');
    v_other_phone := coalesce(v_other_phone, v_listing_phone);

    insert into public.chat_participants (
      conversation_id,
      user_id,
      display_name,
      phone
    )
    values
      (v_conversation_id, auth.uid(), v_me_name, v_me_phone),
      (v_conversation_id, v_listing_owner, v_other_name, v_other_phone)
    on conflict (conversation_id, user_id) do nothing;
  end if;

  return v_conversation_id;
end;
$$;

revoke all on function public.start_listing_conversation(uuid, uuid, text) from public;
grant execute on function public.start_listing_conversation(uuid, uuid, text) to authenticated;

drop function if exists public.get_my_conversations();

create function public.get_my_conversations()
returns table (
  id uuid,
  listing_id uuid,
  listing_title text,
  other_user_id uuid,
  other_name text,
  other_phone text,
  last_message text,
  last_message_at timestamptz,
  unread_count bigint,
  other_last_seen timestamptz
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select
    c.id,
    c.listing_id,
    c.listing_title,
    other_person.user_id,
    other_person.display_name,
    other_person.phone,
    case
      when nullif(trim(last_message.body), '') is not null then last_message.body
      when last_message.file_path is not null then 'Attachment'
      else null
    end as last_message,
    last_message.created_at,
    (
      select count(*)
      from public.chat_messages unread
      where unread.conversation_id = c.id
        and unread.sender_id <> auth.uid()
        and unread.created_at > me.last_read_at
    ) as unread_count,
    p.last_seen
  from public.chat_conversations c
  join public.chat_participants me
    on me.conversation_id = c.id
   and me.user_id = auth.uid()
  join public.chat_participants other_person
    on other_person.conversation_id = c.id
   and other_person.user_id <> auth.uid()
  left join public.profiles p
    on p.id = other_person.user_id
  left join lateral (
    select body, file_path, created_at
    from public.chat_messages
    where conversation_id = c.id
    order by created_at desc
    limit 1
  ) last_message on true
  order by coalesce(last_message.created_at, c.updated_at) desc;
$$;

revoke all on function public.get_my_conversations() from public;
grant execute on function public.get_my_conversations() to authenticated;

drop function if exists public.get_conversation_messages(uuid);

create function public.get_conversation_messages(p_conversation_id uuid)
returns setof public.chat_messages
language sql
security definer
set search_path = public, pg_temp
as $$
  select m.*
  from public.chat_messages m
  where m.conversation_id = p_conversation_id
    and public.is_chat_participant(p_conversation_id)
  order by m.created_at asc
  limit 500;
$$;

revoke all on function public.get_conversation_messages(uuid) from public;
grant execute on function public.get_conversation_messages(uuid) to authenticated;

drop function if exists public.send_chat_message(uuid, text, text, text, text);
drop function if exists public.get_daily_message_remaining();

create function public.get_daily_message_remaining()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_plan text;
  v_used integer;
  v_day_start timestamptz;
begin
  if auth.uid() is null then
    return 0;
  end if;

  select subscription_plan
  into v_plan
  from public.profiles
  where id = auth.uid();

  if coalesce(v_plan, 'standard') = 'pro' then
    return 999999;
  end if;

  v_day_start := (
    date_trunc('day', now() at time zone 'Africa/Johannesburg')
    at time zone 'Africa/Johannesburg'
  );

  select count(*)
  into v_used
  from public.chat_messages
  where sender_id = auth.uid()
    and created_at >= v_day_start;

  return greatest(0, 50 - v_used);
end;
$$;

revoke all on function public.get_daily_message_remaining() from public;
grant execute on function public.get_daily_message_remaining() to authenticated;

create function public.send_chat_message(
  p_conversation_id uuid,
  p_body text,
  p_file_path text default null,
  p_file_name text default null,
  p_file_type text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_remaining integer;
  v_message_id uuid;
  v_expected_prefix text;
begin
  if auth.uid() is null then
    raise exception 'Sign in required';
  end if;

  if not public.is_chat_participant(p_conversation_id) then
    raise exception 'Not authorised';
  end if;

  v_remaining := public.get_daily_message_remaining();

  if v_remaining <= 0 then
    raise exception 'Daily message limit reached';
  end if;

  if char_length(coalesce(p_body, '')) > 4000 then
    raise exception 'Message is too long';
  end if;

  if coalesce(trim(p_body), '') = '' and p_file_path is null then
    raise exception 'Empty message';
  end if;

  if p_file_path is not null then
    v_expected_prefix := p_conversation_id::text || '/' || auth.uid()::text || '/';

    if left(p_file_path, length(v_expected_prefix)) <> v_expected_prefix then
      raise exception 'Invalid attachment path';
    end if;
  end if;

  insert into public.chat_messages (
    conversation_id,
    sender_id,
    body,
    file_path,
    file_name,
    file_type
  )
  values (
    p_conversation_id,
    auth.uid(),
    coalesce(trim(p_body), ''),
    p_file_path,
    p_file_name,
    p_file_type
  )
  returning id into v_message_id;

  update public.chat_conversations
  set updated_at = now()
  where id = p_conversation_id;

  update public.profiles
  set last_seen = now(),
      updated_at = now()
  where id = auth.uid();

  return jsonb_build_object(
    'id', v_message_id,
    'remaining', case
      when v_remaining >= 999999 then 999999
      else greatest(0, v_remaining - 1)
    end
  );
end;
$$;

revoke all on function public.send_chat_message(uuid, text, text, text, text) from public;
grant execute on function public.send_chat_message(uuid, text, text, text, text) to authenticated;

drop function if exists public.mark_conversation_read(uuid);

create function public.mark_conversation_read(p_conversation_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_chat_participant(p_conversation_id) then
    raise exception 'Not authorised';
  end if;

  update public.chat_participants
  set last_read_at = now()
  where conversation_id = p_conversation_id
    and user_id = auth.uid();

  update public.profiles
  set last_seen = now(),
      updated_at = now()
  where id = auth.uid();
end;
$$;

revoke all on function public.mark_conversation_read(uuid) from public;
grant execute on function public.mark_conversation_read(uuid) to authenticated;

drop function if exists public.get_unread_chat_count();

create function public.get_unread_chat_count()
returns bigint
language sql
security definer
set search_path = public, pg_temp
as $$
  select count(*)
  from public.chat_messages m
  join public.chat_participants p
    on p.conversation_id = m.conversation_id
   and p.user_id = auth.uid()
  where m.sender_id <> auth.uid()
    and m.created_at > p.last_read_at;
$$;

revoke all on function public.get_unread_chat_count() from public;
grant execute on function public.get_unread_chat_count() to authenticated;

-- -----------------------------------------------------------------------------
-- 7. REALTIME FOR NEW CHAT MESSAGES
-- -----------------------------------------------------------------------------

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

-- Finished.


-- -----------------------------------------------------------------------------
-- 8. CLAIM OLDER DEVICE-OWNED LISTINGS FOR GUEST MESSAGING
-- -----------------------------------------------------------------------------

create or replace function public.claim_guest_listings(p_owner_key text)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer;
begin
  if auth.uid() is null then
    raise exception 'Guest session required';
  end if;

  if length(coalesce(p_owner_key, '')) < 20 then
    raise exception 'Invalid owner key';
  end if;

  update public.job_listings
  set user_id = auth.uid()
  where owner_key = p_owner_key
    and (user_id is null or user_id = auth.uid());

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.claim_guest_listings(text) from public;
grant execute on function public.claim_guest_listings(text) to authenticated;
