-- LoadLink privacy-friendly listing analytics.
-- Run this once in Supabase SQL Editor after the existing job-listing SQL.

create extension if not exists pgcrypto;

alter table public.job_listings
add column if not exists owner_key text not null default '';

alter table public.job_listings
add column if not exists view_count integer not null default 0;

alter table public.job_listings
add column if not exists last_viewed_at timestamptz;

create table if not exists public.job_view_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.job_listings(id) on delete cascade,
  viewer_hash text not null,
  device_type text not null default 'unknown',
  source text not null default 'direct',
  viewed_at timestamptz not null default now()
);

create index if not exists job_view_events_job_time_idx
on public.job_view_events (job_id, viewed_at desc);

alter table public.job_view_events enable row level security;

-- Events are only written and read through protected functions.
drop policy if exists "no_direct_view_event_access" on public.job_view_events;
create policy "no_direct_view_event_access"
on public.job_view_events
for all
using (false)
with check (false);

create or replace function public.record_job_view(
  p_job_id uuid,
  p_viewer_key text,
  p_device_type text default 'unknown',
  p_source text default 'direct'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  listing_owner text;
  viewer_hash_value text;
  already_recorded boolean;
begin
  select owner_key into listing_owner
  from public.job_listings
  where id = p_job_id;

  if listing_owner is null then
    return false;
  end if;

  if length(coalesce(p_viewer_key, '')) < 8 or listing_owner = p_viewer_key then
    return false;
  end if;

  viewer_hash_value := encode(digest(p_viewer_key, 'sha256'), 'hex');

  select exists (
    select 1
    from public.job_view_events
    where job_id = p_job_id
      and viewer_hash = viewer_hash_value
      and viewed_at > now() - interval '30 minutes'
  ) into already_recorded;

  if already_recorded then
    return false;
  end if;

  insert into public.job_view_events (job_id, viewer_hash, device_type, source)
  values (
    p_job_id,
    viewer_hash_value,
    case when p_device_type in ('mobile','tablet','desktop') then p_device_type else 'unknown' end,
    case when p_source in ('direct','google','social','whatsapp','loadlink','referral') then p_source else 'other' end
  );

  update public.job_listings
  set view_count = coalesce(view_count, 0) + 1,
      last_viewed_at = now()
  where id = p_job_id;

  return true;
end;
$$;

create or replace function public.get_job_analytics(
  p_job_id uuid,
  p_owner_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  listing_record public.job_listings%rowtype;
  result jsonb;
begin
  select * into listing_record
  from public.job_listings
  where id = p_job_id
    and owner_key = p_owner_key
    and length(coalesce(p_owner_key, '')) > 20;

  if listing_record.id is null then
    raise exception 'Not authorised';
  end if;

  select jsonb_build_object(
    'total_views', coalesce(listing_record.view_count, 0),
    'unique_viewers', (
      select count(distinct viewer_hash)
      from public.job_view_events
      where job_id = p_job_id
    ),
    'last_viewed_at', listing_record.last_viewed_at,
    'daily_views', (
      select coalesce(jsonb_agg(jsonb_build_object('label', to_char(day_value, 'Dy'), 'count', view_total) order by day_value), '[]'::jsonb)
      from (
        select day_value,
          (select count(*) from public.job_view_events e where e.job_id = p_job_id and e.viewed_at >= day_value and e.viewed_at < day_value + interval '1 day') as view_total
        from generate_series(date_trunc('day', now()) - interval '6 days', date_trunc('day', now()), interval '1 day') as days(day_value)
      ) daily
    ),
    'devices', (
      select coalesce(jsonb_agg(jsonb_build_object('label', device_type, 'count', total) order by total desc), '[]'::jsonb)
      from (
        select device_type, count(*) as total
        from public.job_view_events
        where job_id = p_job_id
        group by device_type
      ) grouped_devices
    ),
    'sources', (
      select coalesce(jsonb_agg(jsonb_build_object('label', source, 'count', total) order by total desc), '[]'::jsonb)
      from (
        select source, count(*) as total
        from public.job_view_events
        where job_id = p_job_id
        group by source
      ) grouped_sources
    )
  ) into result;

  return result;
end;
$$;

grant execute on function public.record_job_view(uuid, text, text, text) to anon, authenticated;
grant execute on function public.get_job_analytics(uuid, text) to anon, authenticated;
