import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";
import type { NextRequest } from "next/server";

function obj(value:unknown):Record<string,any>{if(value&&typeof value==="object")return value as Record<string,any>;if(typeof value==="string")try{return JSON.parse(value)}catch{}return{}}
function planFromCode(code:string){if(code&&code===process.env.PAYSTACK_DEALER_PLAN_CODE)return"dealer";if(code&&code===process.env.PAYSTACK_PRO_PLAN_CODE)return"pro";return""}
function codeFrom(data:any){return String(data?.plan?.plan_code||data?.plan_code||obj(data?.metadata)?.paystack_plan_code||"")}

export async function POST(request:NextRequest){
 const secret=process.env.PAYSTACK_SECRET_KEY,url=process.env.NEXT_PUBLIC_SUPABASE_URL,service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!secret||!url||!service)return Response.json({error:"Payment service is not configured."},{status:503});
 const raw=await request.text(),expected=crypto.createHmac("sha512",secret).update(raw).digest("hex"),supplied=request.headers.get("x-paystack-signature")||"";if(!supplied||supplied.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))return Response.json({error:"Invalid signature."},{status:401});
 const event=JSON.parse(raw),data=event?.data||{},admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 try{
  if(event.event==="charge.success"){
   const reference=String(data.reference||"");if(!reference)return Response.json({ok:true});const vr=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret}`},cache:"no-store"});const v=await vr.json();if(!vr.ok||!v?.status||v?.data?.status!=="success")return Response.json({error:"Payment could not be verified."},{status:400});
   let p=await admin.from("admin_payments").select("id,user_id,package_type,status,amount_cents,currency,reference,metadata").eq("reference",reference).maybeSingle();if(p.error)throw p.error;
   if(!p.data){const vd=v.data||{},meta=obj(vd.metadata);let userId=String(meta.loadlink_user_id||""),plan=String(meta.loadlink_plan||"");if(!plan)plan=planFromCode(codeFrom(vd));const email=String(vd?.customer?.email||"");if(!userId&&email){const pr=await admin.from("profiles").select("id").ilike("email",email).limit(1).maybeSingle();userId=String(pr.data?.id||"")}if(!userId||!["pro","dealer"].includes(plan))return Response.json({ok:true});const expectedPlan=await admin.from("subscription_plans").select("price_cents,currency").eq("code",plan).eq("is_active",true).maybeSingle();if(!expectedPlan.data)return Response.json({ok:true});if(Number(vd.amount)!==Number(expectedPlan.data.price_cents)||String(vd.currency||"").toUpperCase()!==String(expectedPlan.data.currency||"ZAR").toUpperCase())return Response.json({error:"Recurring payment amount did not match the LoadLink plan."},{status:409});const ins=await admin.from("admin_payments").insert({user_id:userId,amount_cents:Number(vd.amount),currency:String(vd.currency||"ZAR"),status:"initialized",provider:"paystack",reference,external_reference:reference,provider_transaction_id:String(vd.id||""),payer_email:email||null,payment_type:"subscription",package_type:plan,description:`LoadLink ${plan} subscription renewal`,metadata:{recurring:true,paystack_plan_code:codeFrom(vd)||null}}).select("id,user_id,package_type,status,amount_cents,currency,reference,metadata").single();if(ins.error){p=await admin.from("admin_payments").select("id,user_id,package_type,status,amount_cents,currency,reference,metadata").eq("reference",reference).maybeSingle()}else p={data:ins.data,error:null} as any;}
   if(!p.data)return Response.json({ok:true});if(Number(v.data.amount)!==Number(p.data.amount_cents)||String(v.data.currency||"").toUpperCase()!==String(p.data.currency||"ZAR").toUpperCase())return Response.json({error:"Payment details did not match the approved LoadLink plan."},{status:409});const f=await admin.rpc("loadlink_finalize_paid_plan",{p_payment_id:p.data.id,p_reference:reference,p_provider_transaction_id:String(v.data.id||""),p_amount_cents:Number(v.data.amount),p_currency:String(v.data.currency||"ZAR")});if(f.error)throw f.error;return Response.json({ok:true});
  }
  if(event.event==="subscription.create"){
   const sub=String(data.subscription_code||""),planCode=codeFrom(data),plan=planFromCode(planCode),email=String(data?.customer?.email||"");if(!sub||!plan||!email)return Response.json({ok:true});const pr=await admin.from("profiles").select("id").ilike("email",email).limit(1).maybeSingle(),userId=String(pr.data?.id||"");if(!userId)return Response.json({ok:true});const row=await admin.from("user_subscriptions").select("id,metadata").eq("user_id",userId).eq("plan_code",plan).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(row.data?.id)await admin.from("user_subscriptions").update({metadata:{...obj(row.data.metadata),paystack_subscription_code:sub,paystack_plan_code:planCode,paystack_customer_code:String(data?.customer?.customer_code||""),next_payment_date:data.next_payment_date||null}}).eq("id",row.data.id);return Response.json({ok:true});
  }
  if(event.event==="invoice.payment_failed"){
   const sub=String(data?.subscription?.subscription_code||data?.subscription_code||"");if(!sub)return Response.json({ok:true});const row=await admin.from("user_subscriptions").select("id,user_id,plan_code").contains("metadata",{paystack_subscription_code:sub}).limit(1).maybeSingle();if(row.data?.id){await admin.from("user_subscriptions").update({status:"past_due",suspension_reason:"Recurring payment failed"}).eq("id",row.data.id);await admin.from("loadlink_subscriptions").update({status:"past_due",suspension_reason:"Recurring payment failed"}).eq("user_id",row.data.user_id).eq("plan_code",row.data.plan_code);await admin.from("user_notifications").insert({user_id:row.data.user_id,type:"payment_failed",title:"Your LoadLink payment needs attention",message:"The latest renewal did not complete. Update your payment method to keep paid features active.",action_url:"/packages?manage=1",metadata:{plan:row.data.plan_code,subscription_code:sub}})}return Response.json({ok:true});
  }
  if(event.event==="subscription.not_renew"||event.event==="subscription.disable"){
   const sub=String(data.subscription_code||"");if(!sub)return Response.json({ok:true});const row=await admin.from("user_subscriptions").select("id,user_id,plan_code").contains("metadata",{paystack_subscription_code:sub}).limit(1).maybeSingle();if(row.data?.id){const status=event.event==="subscription.not_renew"?"cancelled":"expired";await admin.from("user_subscriptions").update({status,cancelled_at:status==="cancelled"?new Date().toISOString():null}).eq("id",row.data.id);await admin.from("loadlink_subscriptions").update({status,cancelled_at:status==="cancelled"?new Date().toISOString():null}).eq("user_id",row.data.user_id).eq("plan_code",row.data.plan_code);await admin.from("user_notifications").insert({user_id:row.data.user_id,type:status==="cancelled"?"plan_cancelled":"plan_expired",title:status==="cancelled"?"Your LoadLink plan will not renew":"Your LoadLink plan has ended",message:status==="cancelled"?"Your current paid period stays available until it ends.":"Renew when you are ready to advertise vehicles again.",action_url:"/packages",metadata:{plan:row.data.plan_code,subscription_code:sub}})}return Response.json({ok:true});
  }
  return Response.json({ok:true});
 }catch(error){console.error("LoadLink Paystack webhook error",error);return Response.json({error:"Webhook processing failed."},{status:500})}
}
