"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import AuthStatusButton from "@/components/AuthStatusButton";
import HomeLogoLink from "@/components/HomeLogoLink";
import LoadLinkLoading from "@/components/LoadLinkLoading";
import LoadLinkThemeToggle from "@/components/LoadLinkThemeToggle";
import SiteMenu from "@/components/SiteMenu";
import { getLoadLinkIntelligence } from "@/lib/loadlinkIntelligence";
import { inspectLoadLinkImage, showLoadLinkImageQuality } from "@/lib/loadlinkImageQuality";
import { createSafeRandomId, imageExtension, inferUploadContentType, prepareImageFileForForm, readableUploadError, validateImageFile } from "@/lib/mobilePosting";
import { isSupabaseConfigured, supabase } from "@/lib/supabaseClient";
import { useLoadLinkTheme } from "@/lib/useLoadLinkTheme";

type VehicleGroup="Catering / Event"|"Trucks / Trailers"|"Farming / Mining";
const groups:VehicleGroup[]=["Trucks / Trailers","Catering / Event","Farming / Mining"];
const cities=["Johannesburg","Pretoria","Centurion","Midrand","Sandton","Durban","Cape Town","Gqeberha","East London","Bloemfontein","Polokwane","Mbombela","Rustenburg","Kimberley","Mthatha"];
const today=()=>{const n=new Date();return new Date(n.getTime()-n.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const cleanPhone=(v:string)=>v.replace(/[^\d+]/g,"");const validPhone=(v:string)=>/^0\d{9}$/.test(cleanPhone(v))||/^\+27\d{9}$/.test(cleanPhone(v));

export default function ListJobPage(){
 const router=useRouter(),{darkMode,toggleTheme}=useLoadLinkTheme();const [ready,setReady]=useState(false),[step,setStep]=useState(1),[group,setGroup]=useState<VehicleGroup>("Trucks / Trailers"),[vehicleNeeded,setVehicleNeeded]=useState(""),[neededOn,setNeededOn]=useState(today()),[city,setCity]=useState("Johannesburg"),[title,setTitle]=useState(""),[rate,setRate]=useState(""),[description,setDescription]=useState(""),[postedBy,setPostedBy]=useState(""),[contact,setContact]=useState(""),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[success,setSuccess]=useState(false);const submission=useRef("");
 const surface=darkMode?"border-white/10 bg-[#0c0c0c] text-white":"border-black/10 bg-white text-black";const input=`h-13 w-full rounded-xl border px-4 text-sm font-semibold outline-none focus:border-[#f6b800] ${darkMode?"border-white/12 bg-[#151515] text-white placeholder:text-white/30":"border-black/10 bg-[#faf8f2] text-black placeholder:text-black/35"}`;
 useEffect(()=>{void(async()=>{if(!isSupabaseConfigured){router.replace('/login');return}const intelligence=await getLoadLinkIntelligence();if(!intelligence.authenticated){router.replace(`/login?returnTo=${encodeURIComponent('/jobs/list')}`);return}if(["blocked","suspended"].includes(intelligence.account_status))setMessage(intelligence.account_reason||"You cannot post while this account is restricted.");const{data:auth}=await supabase.auth.getUser();if(auth.user){const profile=await supabase.from("profiles").select("full_name,company_name,phone").eq("id",auth.user.id).maybeSingle();setPostedBy(String(profile.data?.company_name||profile.data?.full_name||auth.user.user_metadata?.full_name||""));setContact(String(profile.data?.phone||""));const key=`loadlink-job-submission-id:${auth.user.id}`;submission.current=localStorage.getItem(key)||createSafeRandomId();localStorage.setItem(key,submission.current);const draft=localStorage.getItem(`loadlink-job-draft-v272:${auth.user.id}`);if(draft)try{const d=JSON.parse(draft);setGroup(d.group||"Trucks / Trailers");setVehicleNeeded(d.vehicleNeeded||"");setNeededOn(d.neededOn||today());setCity(d.city||"Johannesburg");setTitle(d.title||"");setRate(d.rate||"");setDescription(d.description||"");setPostedBy(d.postedBy||profile.data?.company_name||profile.data?.full_name||"");setContact(d.contact||profile.data?.phone||"");setStep(Math.min(5,Math.max(1,Number(d.step||1))))}catch{}}setReady(true)})().catch(()=>setReady(true))},[router]);
 useEffect(()=>{if(!ready)return;let active=true;void supabase.auth.getUser().then(({data})=>{if(!active||!data.user)return;localStorage.setItem(`loadlink-job-draft-v272:${data.user.id}`,JSON.stringify({group,vehicleNeeded,neededOn,city,title,rate,description,postedBy,contact,step}))});return()=>{active=false}},[ready,group,vehicleNeeded,neededOn,city,title,rate,description,postedBy,contact,step]);
 async function photos(e:ChangeEvent<HTMLInputElement>){const selected=Array.from(e.target.files||[]).slice(0,5);e.target.value="";setMessage("");const next:File[]=[],urls:string[]=[];try{for(const source of selected){const validation=validateImageFile(source,source.name||"Job photo");if(validation)throw new Error(validation);const quality=await inspectLoadLinkImage(source);showLoadLinkImageQuality(quality.messages);const prepared=await prepareImageFileForForm(source,{maxWidth:1440,maxHeight:1440,quality:.76,namePrefix:"loadlink-job"});next.push(prepared.file);urls.push(prepared.previewUrl)}setFiles(next);setPreviews(urls)}catch(error){setMessage(readableUploadError(error,"One selected photo could not be prepared."))}}
 function next(){setMessage("");if(step===1&&!vehicleNeeded.trim())return setMessage("Tell LoadLink what vehicle or mobile unit is needed.");if(step===2&&(neededOn<today()||!city.trim()))return setMessage(neededOn<today()?"That date has already passed. Choose today or a future date.":"Choose the job location.");if(step===3&&(!title.trim()||!description.trim()))return setMessage("Add a short title and enough job detail for an operator to understand the work.");if(step===4&&(!postedBy.trim()||!validPhone(contact)))return setMessage(!postedBy.trim()?"Add the contact or company name.":"Enter a valid South African contact number.");setStep(v=>Math.min(5,v+1))}
 async function upload(userId:string){const urls:string[]=[];for(let i=0;i<files.length;i++){const f=files[i],type=inferUploadContentType(f),path=`${userId}/jobs/${submission.current}/${i}.${imageExtension(type)}`,r=await supabase.storage.from("job-photos").upload(path,f,{cacheControl:"3600",contentType:type,upsert:true});if(r.error)throw r.error;urls.push(supabase.storage.from("job-photos").getPublicUrl(path).data.publicUrl)}return urls}
 async function submit(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setMessage("");try{const intelligence=await getLoadLinkIntelligence();if(!intelligence.authenticated)throw new Error("Sign in to post this job.");if(["blocked","suspended"].includes(intelligence.account_status))throw new Error(intelligence.account_reason||"You cannot post while this account is restricted.");if(neededOn<today())throw new Error("That date has already passed. Choose today or a future date.");const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Your sign-in session needs to be refreshed.");const photoUrls=await upload(auth.user.id);const r=await supabase.rpc("loadlink_submit_job",{p_title:title.trim(),p_city:city.trim(),p_vehicle_group:group,p_vehicle_needed:vehicleNeeded.trim(),p_needed_on:neededOn,p_rate:rate.trim(),p_posted_by:postedBy.trim(),p_contact_number:contact.trim(),p_description:description.trim(),p_photos:photoUrls,p_client_request_id:submission.current});if(r.error)throw r.error;localStorage.removeItem(`loadlink-job-draft-v272:${auth.user.id}`);localStorage.removeItem(`loadlink-job-submission-id:${auth.user.id}`);setSuccess(true);window.dispatchEvent(new Event("loadlink-account-state-changed"))}catch(error){const raw=error instanceof Error?error.message:String(error||"");setMessage(/postgres|supabase|row level security|pgrst/i.test(raw)?"LoadLink could not publish this job right now. Your information is still saved.":raw||"LoadLink could not publish this job right now.")}finally{setSaving(false)}}
 if(!ready)return <main className={darkMode?"min-h-screen bg-black text-white":"min-h-screen bg-[#f4f0e7] text-black"}><LoadLinkLoading/></main>;
 if(success)return <main className={darkMode?"min-h-screen bg-black text-white":"min-h-screen bg-[#f4f0e7] text-black"}><Header darkMode={darkMode} toggleTheme={toggleTheme}/><div className="mx-auto flex min-h-[calc(100vh-64px)] max-w-xl items-center px-4"><div className={`w-full rounded-[26px] border p-7 text-center ${surface}`}><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#f6b800] text-3xl font-black text-black">✓</div><h1 className="mt-5 text-3xl font-black">Job submitted</h1><p className="mt-2 text-xs font-semibold opacity-50">LoadLink received the job and connected it to your account.</p><button onClick={()=>router.push('/jobs')} className="mt-6 h-12 rounded-xl bg-[#f6b800] px-5 text-sm font-black text-black">View jobs</button></div></div></main>;
 return <main className={darkMode?"min-h-screen bg-black text-white":"min-h-screen bg-[#f4f0e7] text-black"}><Header darkMode={darkMode} toggleTheme={toggleTheme}/><section className="border-b border-[#f6b800]/25 bg-black text-white"><div className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-[40px] font-black tracking-[-.06em]">Post a job</h1><p className="mt-2 text-xs font-semibold text-white/50">Job posting is free.</p></div></section><form onSubmit={submit} className="mx-auto max-w-3xl px-4 py-6 pb-16"><div className="mb-4 h-1 overflow-hidden rounded-full bg-current/10"><div className="h-full bg-[#f6b800]" style={{width:`${step*20}%`}}/></div><section className={`rounded-[24px] border p-5 sm:p-7 ${surface}`}>
 {step===1?<><h2 className="text-2xl font-black">What do you need?</h2><div className="mt-5 grid gap-3"><label><span className="mb-2 block text-[10px] font-black opacity-45">Category</span><select value={group} onChange={e=>setGroup(e.target.value as VehicleGroup)} className={input}>{groups.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-2 block text-[10px] font-black opacity-45">Vehicle or unit needed</span><input value={vehicleNeeded} onChange={e=>setVehicleNeeded(e.target.value)} placeholder="e.g. Side tipper, Lowbed, Mobile fridge" className={input}/></label></div></>:null}
 {step===2?<><h2 className="text-2xl font-black">When and where?</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label><span className="mb-2 block text-[10px] font-black opacity-45">Needed on</span><input type="date" data-loadlink-future-date="true" value={neededOn} min={today()} onChange={e=>setNeededOn(e.target.value)} className={input}/></label><label><span className="mb-2 block text-[10px] font-black opacity-45">Location</span><input list="loadlink-job-cities" value={city} onChange={e=>setCity(e.target.value)} className={input}/><datalist id="loadlink-job-cities">{cities.map(x=><option key={x} value={x}/>)}</datalist></label></div></>:null}
 {step===3?<><h2 className="text-2xl font-black">Job details</h2><div className="mt-5 grid gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Short job title" className={input}/><input value={rate} onChange={e=>setRate(e.target.value)} placeholder="Rate / budget — optional" className={input}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Route, load, requirements and anything an operator should know" className={`${input} min-h-36 py-4`}/></div></>:null}
 {step===4?<><h2 className="text-2xl font-black">Contact</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={postedBy} onChange={e=>setPostedBy(e.target.value)} placeholder="Your name or company" className={input}/><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="0821234567" className={input}/></div><label className="mt-4 block rounded-[18px] border border-current/10 p-4"><span className="text-xs font-black">Photos — optional</span><input type="file" accept="image/*" multiple onChange={photos} className="mt-3 block w-full text-xs"/></label>{previews.length?<div className="mt-3 grid grid-cols-3 gap-2">{previews.map((u,i)=><img key={`${u}-${i}`} src={u} alt="" className="aspect-square w-full rounded-xl object-cover"/>)}</div>:null}</>:null}
 {step===5?<><h2 className="text-2xl font-black">Review</h2><div className="mt-5 divide-y divide-current/10 rounded-[18px] border border-current/10"><Review label="Need" value={vehicleNeeded}/><Review label="Date" value={new Date(`${neededOn}T12:00:00`).toLocaleDateString("en-ZA",{day:"numeric",month:"short",year:"numeric"})}/><Review label="Location" value={city}/><Review label="Job" value={title}/><Review label="Contact" value={`${postedBy} · ${contact}`}/></div></>:null}
 {message?<div className="mt-5 rounded-[16px] border border-[#f6b800]/35 bg-[#f6b800]/10 p-3 text-xs font-bold">{message}</div>:null}<div className="mt-6 flex gap-2">{step>1?<button type="button" onClick={()=>{setMessage("");setStep(v=>v-1)}} className="h-12 rounded-xl border border-current/10 px-5 text-xs font-black">Back</button>:null}{step<5?<button type="button" onClick={next} className="h-12 flex-1 rounded-xl bg-[#f6b800] text-sm font-black text-black">Continue</button>:<button type="submit" disabled={saving} className="h-12 flex-1 rounded-xl bg-[#f6b800] text-sm font-black text-black disabled:opacity-45">{saving?"Submitting…":"Submit job"}</button>}</div></section></form></main>;
}
function Header({darkMode,toggleTheme}:{darkMode:boolean;toggleTheme:()=>void}){return <header className={`sticky top-0 z-50 h-[64px] border-b ${darkMode?"border-white/10 bg-black":"border-black/10 bg-white"}`}><div className="relative mx-auto flex h-full max-w-[1500px] items-center px-3 sm:px-5"><div className="flex items-center gap-1.5"><SiteMenu darkMode={darkMode}/><AuthStatusButton darkMode={darkMode}/></div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><HomeLogoLink theme={darkMode?"dark":"light"}/></div><div className="ml-auto"><LoadLinkThemeToggle darkMode={darkMode} onToggle={toggleTheme}/></div></div></header>}
function Review({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 px-4 py-3"><span className="text-[9px] font-black uppercase opacity-35">{label}</span><span className="text-right text-xs font-bold">{value||"—"}</span></div>}
