"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import HomeLogoLink from "@/components/HomeLogoLink";
import { syncAccountState } from "@/lib/accountState";
import { isAuthenticatedUser, safeNextPath } from "@/lib/auth";
import { recoverySupabase } from "@/lib/recoverySupabase";
import { isFourDigitCode, markSecurityCodeVerified } from "@/lib/securityCode";
import { supabase } from "@/lib/supabaseClient";
import { useLoadLinkTheme } from "@/lib/useLoadLinkTheme";

type Mode="checking"|"verify"|"error"; type CodeStatus={enabled?:boolean}; type VerifyResult={ok?:boolean;reason?:string;attempts_remaining?:number;needs_setup?:boolean};
export default function SecurityCodePage(){
 const router=useRouter(); const {darkMode}=useLoadLinkTheme(); const [mode,setMode]=useState<Mode>("checking"),[code,setCode]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[email,setEmail]=useState("");
 function nextPath(){return safeNextPath(new URLSearchParams(window.location.search).get("next"),"/");}
 async function enter(){const {data:{session}}=await supabase.auth.getSession();markSecurityCodeVerified(session);await syncAccountState().catch(()=>undefined);router.replace(nextPath());}
 useEffect(()=>{let active=true;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session||!isAuthenticatedUser(session.user)){router.replace(`/login?next=${encodeURIComponent(nextPath())}`);return;}setEmail(session.user.email||"");const {data,error}=await supabase.rpc("loadlink_security_code_status");if(!active)return;if(error){setMode("error");setMessage("This sign-in step is temporarily unavailable.");return;}if(!((data||{}) as CodeStatus).enabled){await enter();return;}setMode("verify");})();return()=>{active=false};},[router]);
 async function submit(e:FormEvent){e.preventDefault();if(busy||!isFourDigitCode(code))return;setBusy(true);setMessage("");try{const {data,error}=await supabase.rpc("loadlink_verify_security_code",{p_code:code});if(error)throw error;const r=(data||{}) as VerifyResult;if(r.ok||r.needs_setup||r.reason==="setup_required"){await enter();return;}setCode("");setMessage(r.reason==="locked"?"Too many attempts. Try again in 15 minutes or use email recovery.":typeof r.attempts_remaining==="number"?`Incorrect code. ${r.attempts_remaining} attempt${r.attempts_remaining===1?"":"s"} left.`:"Incorrect code.");}catch{setMessage("The code could not be checked right now.");}finally{setBusy(false)}}
 async function recover(){if(busy||!email)return;setBusy(true);setMessage("");try{const redirectTo=`${window.location.origin}/auth/code-recovery?next=${encodeURIComponent(nextPath())}`;const {error}=await recoverySupabase.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo,shouldCreateUser:false}});if(error)throw error;setMessage("Recovery email sent.");}catch{setMessage("Recovery email could not be sent right now.");}finally{setBusy(false)}}
 return <main className={`min-h-[100dvh] px-5 py-8 ${darkMode?"bg-black text-white":"bg-[#f4efe3] text-black"}`}><div className="mx-auto flex min-h-[calc(100dvh-4rem)] max-w-md flex-col justify-center"><div className="mb-7 flex justify-center"><HomeLogoLink theme={darkMode?"dark":"light"}/></div><section className={`overflow-hidden rounded-[30px] border shadow-[0_18px_60px_rgba(0,0,0,.08)] ${darkMode?"border-white/10 bg-[#0b0b0b]":"border-black/10 bg-white"}`}><div className="p-6 md:p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-black text-[#f6b800]"><span className="text-lg font-black">••••</span></div><p className={`mt-5 text-[10px] font-black uppercase tracking-[.18em] ${darkMode?"text-[#f6b800]":"text-[#8b6800]"}`}>Protected sign-in</p><h1 className="mt-2 text-3xl font-black tracking-[-.045em]">Enter your LoadLink code</h1><p className={`mt-2 text-sm font-semibold leading-6 ${darkMode?"text-white/52":"text-black/52"}`}>This account uses an optional 4-digit sign-in code after the password step.</p>{mode==="verify"?<form onSubmit={submit} className="mt-6"><input aria-label="4-digit LoadLink code" inputMode="numeric" autoComplete="one-time-code" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} autoFocus placeholder="••••" className={`h-16 w-full rounded-2xl border px-5 text-center text-3xl font-black tracking-[.45em] outline-none transition focus:border-[#f6b800] ${darkMode?"border-white/12 bg-white/[.04] text-white placeholder:text-white/20":"border-black/10 bg-[#faf8f2] text-black placeholder:text-black/20"}`}/><button disabled={busy||code.length!==4} className="mt-4 h-12 w-full rounded-xl bg-[#f6b800] text-sm font-black text-black disabled:opacity-40">{busy?"Checking…":"Continue to LoadLink"}</button><button type="button" onClick={()=>void recover()} disabled={busy||!email} className={`mt-3 h-11 w-full rounded-xl text-sm font-bold disabled:opacity-40 ${darkMode?"text-white/55":"text-black/55"}`}>Forgot code? <span className="underline underline-offset-4">Recover by email</span></button></form>:null}{mode==="checking"?<div className="py-8"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-2 border-current/10 border-t-[#f6b800]"/></div>:null}{mode==="error"?<button onClick={()=>window.location.reload()} className="mt-6 h-12 w-full rounded-xl bg-[#f6b800] text-sm font-black text-black">Try again</button>:null}{message?<p role="status" className={`mt-4 rounded-xl px-3 py-2.5 text-center text-xs font-bold ${message.includes("sent")?(darkMode?"bg-white/[.04] text-white/55":"bg-black/[.03] text-black/55"):"bg-red-500/10 text-red-500"}`}>{message}</p>:null}</div></section><p className={`mt-4 text-center text-[11px] font-semibold ${darkMode?"text-white/35":"text-black/35"}`}>Never share your password, OTP or LoadLink sign-in code.</p></div></main>;
}
