"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import { isSupabaseConfigured, supabase } from "@/lib/supabaseClient";

type ListingMeta = { id?:string|null; title?:string|null; city?:string|null; package_type?:string|null; dealer_package_active?:boolean|null; dealership_slug?:string|null; dealership_showroom_available?:boolean|null };
type DealerPostingGate = { required?:boolean; complete?:boolean; missing?:string[] };
const STYLE_ID="loadlink-marketplace-polish-style";const DEALER_GATE_ID="loadlink-dealer-profile-posting-gate";
function clean(value:unknown){return String(value||"").trim()}

function installStyles(){if(document.getElementById(STYLE_ID))return;const style=document.createElement("style");style.id=STYLE_ID;style.textContent=`
html[data-loadlink-theme="dark"] [class*="bg-[#f6b800]/"]{background-color:rgba(246,184,0,.07)!important;border-color:rgba(246,184,0,.18)!important;-webkit-backdrop-filter:blur(10px) saturate(116%);backdrop-filter:blur(10px) saturate(116%)}
#loadlink-promoted-carousel::-webkit-scrollbar{display:none} input[data-loadlink-future-date="true"]::-webkit-date-and-time-value{text-align:left}
`;document.head.appendChild(style)}
function hideSeenBadges(){document.querySelectorAll<HTMLElement>("button,span,div").forEach(node=>{if(clean(node.textContent).toLowerCase()==="seen")node.style.display="none"})}

export default function MarketplaceUxPolishEnhancer(){const pathname=usePathname();useEffect(()=>{
  if(!["/jobs","/my-posts","/jobs/list"].includes(pathname))return;installStyles();let cancelled=false;const timers:number[]=[];const rows=new Map<string,ListingMeta>();

  function cleanJobsLightMode(){if(pathname!=="/jobs"||document.documentElement.getAttribute("data-loadlink-theme")==="dark")return;const main=document.querySelector<HTMLElement>("main");if(main)main.style.backgroundColor="#fff";document.querySelectorAll<HTMLElement>("section").forEach(section=>{const heading=section.querySelector("h2");if(clean(heading?.textContent).toLowerCase()==="promoted listings")section.style.backgroundColor="#fff"});}
  function rowForCard(card:HTMLElement){const title=clean(card.querySelector("h3")?.textContent).toLowerCase();const city=clean(card.querySelector("p")?.textContent).split("·")[0].trim().toLowerCase();if(!title)return undefined;return Array.from(rows.values()).find(row=>clean(row.title).toLowerCase()===title&&(!city||clean(row.city).toLowerCase()===city))}

  function promotedCarousel(){if(pathname!=="/jobs")return;document.getElementById("loadlink-promoted-carousel-controls")?.remove();document.querySelectorAll("[data-loadlink-public-view-post],[data-loadlink-owner-controls]").forEach(node=>node.remove());const heading=Array.from(document.querySelectorAll<HTMLElement>("h2")).find(node=>clean(node.textContent).toLowerCase()==="promoted listings");const section=heading?.closest("section");const root=heading?.parentElement;if(!heading||!root)return;if(section&&document.documentElement.getAttribute("data-loadlink-theme")!=="dark")section.style.backgroundColor="#fff";
    const rail=Array.from(root.children).map(x=>x as HTMLElement).find(node=>node!==heading&&node.querySelectorAll("img").length>0&&node.querySelectorAll("h3").length>0);if(!rail)return;rail.id="loadlink-promoted-carousel";Object.assign(rail.style,{display:"flex",gap:"12px",overflowX:"auto",overflowY:"hidden",scrollSnapType:"x mandatory",scrollbarWidth:"none",paddingBottom:"8px",gridTemplateColumns:"none"});rail.style.setProperty("-webkit-overflow-scrolling","touch");
    Array.from(rail.children).forEach(child=>{const card=child as HTMLElement;if(!card.querySelector("img")||!card.querySelector("h3")){card.style.display="none";return}card.style.display="block";card.style.flex=window.innerWidth<640?"0 0 min(86vw,390px)":"0 0 min(420px,46vw)";card.style.scrollSnapAlign="start";card.style.scrollSnapStop="always";if(!card.querySelector("[data-loadlink-promoted-view-post]")){const content=card.querySelector<HTMLElement>("div.p-4")||card.lastElementChild as HTMLElement|null;if(content){const hint=document.createElement("span");hint.dataset.loadlinkPromotedViewPost="true";hint.className="mt-3 inline-flex text-[10px] font-black uppercase tracking-[.08em] opacity-60";hint.textContent="View post →";content.appendChild(hint)}}if(card.dataset.loadlinkExactPost==="true")return;const row=rowForCard(card);if(!row?.id)return;card.dataset.loadlinkExactPost="true";card.onclick=event=>{event.preventDefault();window.location.assign(`/listing/${encodeURIComponent(String(row.id))}`)}})}

  function myPostsFixes(){if(pathname!=="/my-posts")return;hideSeenBadges();document.querySelectorAll<HTMLDetailsElement>('details:has(summary[aria-label="More post actions"])').forEach(details=>{const menu=details.querySelector<HTMLElement>("div.absolute");if(!menu)return;if(window.innerWidth<768)Object.assign(menu.style,{position:"fixed",left:"12px",right:"12px",bottom:"calc(env(safe-area-inset-bottom) + 12px)",top:"auto",width:"auto",maxHeight:"64dvh",overflowY:"auto",zIndex:"2147483400"});if(details.dataset.loadlinkContractActionChecked==="true"||!isSupabaseConfigured)return;const article=details.closest("article");const view=article?.querySelector<HTMLAnchorElement>('a[href^="/listing/"]');const listingId=clean(view?.getAttribute("href")?.split("/listing/")[1]?.split(/[?#]/)[0]);if(!listingId)return;details.dataset.loadlinkContractActionChecked="true";void supabase.from("job_listings").select("listing_kind,status").eq("id",listingId).maybeSingle().then(({data,error})=>{if(cancelled||error||clean(data?.listing_kind).toLowerCase()!=="contract"||clean(data?.status||"active").toLowerCase()!=="active"||menu.querySelector('[data-loadlink-cancel-contract="true"]'))return;const button=document.createElement("button");button.type="button";button.dataset.loadlinkCancelContract="true";button.className="block w-full border-t border-[#f6b800]/25 px-4 py-3 text-left text-xs font-black text-[#c28e00]";button.textContent="Cancel contract listing";button.onclick=async event=>{event.preventDefault();event.stopPropagation();if(!window.confirm("Cancel this contract listing? It will stop appearing as an active contract."))return;button.disabled=true;button.textContent="Cancelling…";const result=await supabase.rpc("set_my_listing_status",{p_listing_id:listingId,p_status:"closed",p_owner_key:""});if(result.error||result.data!==true){button.disabled=false;button.textContent="Cancel contract listing";window.dispatchEvent(new CustomEvent("loadlink:toast",{detail:{kind:"error",title:"Contract not cancelled",message:result.error?.message||"LoadLink could not cancel this contract listing.",duration:5200}}));return}window.dispatchEvent(new CustomEvent("loadlink:toast",{detail:{kind:"success",title:"Contract cancelled",message:"The contract listing is now closed.",duration:4200}}));window.setTimeout(()=>window.location.reload(),450)};menu.insertBefore(button,menu.querySelector('button.text-red-500')||null)})})}
  function dateFix(){if(pathname!=="/jobs/list")return;document.querySelectorAll<HTMLInputElement>('input[type="date"]').forEach(input=>{input.style.width="100%";input.style.minWidth="0";input.style.maxWidth="100%";input.style.fontSize="16px";input.style.boxSizing="border-box"})}
  async function dealerGate(){if(pathname!=="/jobs/list"||!isSupabaseConfigured||document.getElementById(DEALER_GATE_ID))return;const auth=await supabase.auth.getUser();if(!auth.data.user||cancelled)return;const result=await supabase.rpc("loadlink_dealer_profile_posting_gate",{p_user_id:auth.data.user.id});const gate=result.data as DealerPostingGate|null;if(result.error||!gate?.required||gate.complete||cancelled)return;const overlay=document.createElement("div");overlay.id=DEALER_GATE_ID;overlay.className="fixed inset-0 z-[2147483550] flex items-end bg-black/75 p-3 sm:items-center sm:justify-center";const panel=document.createElement("section");panel.className="w-full max-w-md rounded-[26px] border border-white/12 bg-[#0b0b0b] p-5 text-white shadow-2xl";const title=document.createElement("h2");title.className="text-2xl font-black tracking-[-.03em]";title.textContent="Finish your Dealer profile";const copy=document.createElement("p");copy.className="mt-3 text-sm font-semibold leading-6 text-white/60";copy.textContent=`Before this Dealer account can post, add: ${(gate.missing||[]).join(", ")||"the missing public dealership details"}.`;const actions=document.createElement("div");actions.className="mt-5 grid gap-2";const finish=document.createElement("a");finish.href="/dealer?section=showroom";finish.className="flex min-h-12 items-center justify-center rounded-[16px] bg-[#f6b800] px-4 text-sm font-black text-black";finish.textContent="Complete Dealer profile";const back=document.createElement("a");back.href="/jobs";back.className="flex min-h-12 items-center justify-center rounded-[16px] border border-white/12 px-4 text-sm font-black text-white";back.textContent="Back";actions.append(finish,back);panel.append(title,copy,actions);overlay.appendChild(panel);document.body.appendChild(overlay)}

  async function initialise(){if(isSupabaseConfigured&&pathname==="/jobs"){const payload=await fetch(`/api/job-listings?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).catch(()=>null);((payload?.rows||[]) as ListingMeta[]).forEach(row=>{if(row.id)rows.set(String(row.id),row)})}if(cancelled)return;const scan=()=>{hideSeenBadges();cleanJobsLightMode();promotedCarousel();myPostsFixes();dateFix()};scan();[100,300,700,1300,2200].forEach(delay=>timers.push(window.setTimeout(scan,delay)));void dealerGate()}
  void initialise();return()=>{cancelled=true;timers.forEach(window.clearTimeout);document.getElementById(DEALER_GATE_ID)?.remove();document.getElementById("loadlink-promoted-carousel-controls")?.remove()}
},[pathname]);return null}
