"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { dealerFetch, formatZar, relativeAge } from "@/lib/dealer/client";
import type { DealerCustomer, DealerStaffMember } from "@/lib/dealer/types";
import { EmptyState, Input, Modal, PrimaryButton, SectionHeading, Select, SecondaryButton, Surface, Textarea } from "./ui";

type CustomerResponse = { items: DealerCustomer[]; total: number; page: number; pages: number };
type TimelineEvent = { id:string; event_type:string; title:string; detail?:string|null; created_at:string };
type Match = { id:string; title:string; price_amount?:number|null; city?:string|null; brand?:string|null; model?:string|null; vehicle_type?:string|null; photo?:string|null; match_reason?:string|null };

export default function DealerCustomers({ darkMode }: { darkMode: boolean }) {
  const [data,setData]=useState<CustomerResponse>({items:[],total:0,page:1,pages:1}); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<DealerCustomer|null>(null); const [timeline,setTimeline]=useState<TimelineEvent[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [team,setTeam]=useState<DealerStaffMember[]>([]); const [noteOpen,setNoteOpen]=useState(false); const [note,setNote]=useState(""); const [notifyUser,setNotifyUser]=useState(""); const [prefOpen,setPrefOpen]=useState(false); const [prefs,setPrefs]=useState({budget_min:"",budget_max:"",preferred_make:"",preferred_vehicle_type:"",preferences:""}); const [error,setError]=useState("");
  async function load(page=1){try{const r=await dealerFetch<CustomerResponse>(`/api/dealer/customers?${new URLSearchParams({page:String(page),q:query})}`);setData(r);if(selected){const fresh=r.items.find(x=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e){setError(e instanceof Error?e.message:"Customers could not be loaded.")}}
  async function detail(customer:DealerCustomer){setSelected(customer); const [t,m]=await Promise.allSettled([dealerFetch<{events:TimelineEvent[]}>(`/api/dealer/customers?customer_id=${customer.id}&timeline=1`),dealerFetch<{items:Match[]}>(`/api/dealer/customers?customer_id=${customer.id}&matches=1`)]); setTimeline(t.status==="fulfilled"?t.value.events||[]:[]);setMatches(m.status==="fulfilled"?m.value.items||[]:[]);}
  useEffect(()=>{const t=setTimeout(()=>void load(1),250);return()=>clearTimeout(t)},[query]); useEffect(()=>{void dealerFetch<{staff:DealerStaffMember[]}>("/api/dealer/team").then(r=>setTeam(r.staff||[])).catch(()=>setTeam([]))},[]);
  async function addNote(){if(!selected||!note.trim())return;await dealerFetch("/api/dealer/customers",{method:"POST",body:JSON.stringify({action:"note",customer_id:selected.id,note:note.trim(),notify_user_id:notifyUser||null})});setNote("");setNotifyUser("");setNoteOpen(false);await detail(selected)}
  function openPrefs(){if(!selected)return;setPrefs({budget_min:selected.budget_min?String(selected.budget_min):"",budget_max:selected.budget_max?String(selected.budget_max):"",preferred_make:selected.preferred_make||"",preferred_vehicle_type:selected.preferred_vehicle_type||"",preferences:(selected.preferences||[]).join(", ")});setPrefOpen(true)}
  async function savePrefs(){if(!selected)return;await dealerFetch("/api/dealer/customers",{method:"POST",body:JSON.stringify({action:"preferences",customer_id:selected.id,...prefs,preferences:prefs.preferences.split(",").map(x=>x.trim()).filter(Boolean)})});setPrefOpen(false);await load(data.page);await detail({...selected,budget_min:prefs.budget_min?Number(prefs.budget_min):null,budget_max:prefs.budget_max?Number(prefs.budget_max):null,preferred_make:prefs.preferred_make||null,preferred_vehicle_type:prefs.preferred_vehicle_type||null,preferences:prefs.preferences.split(",").map(x=>x.trim()).filter(Boolean)})}
  return <div className="grid gap-4">
    <Surface darkMode={darkMode} className="p-4 sm:p-5"><SectionHeading title="Customers" detail="Keep LoadLink enquiries, calls, walk-ins and repeat buyers in one dealership record."/><div className="mt-4"><Input darkMode={darkMode} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or email"/></div>{error?<p className="mt-3 text-sm font-bold text-red-500">{error}</p>:null}</Surface>
    <div className="grid gap-4 xl:grid-cols-[.82fr_1.18fr]">
      <Surface darkMode={darkMode} className="overflow-hidden">{data.items.length?<div className="divide-y divide-current/10">{data.items.map(customer=><button key={customer.id} type="button" onClick={()=>void detail(customer)} className={`w-full px-4 py-4 text-left ${selected?.id===customer.id?(darkMode?"bg-white/[.05]":"bg-black/[.03]"):""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-black">{customer.name}</div><div className="mt-1 truncate text-xs opacity-50">{customer.phone||customer.email||customer.source}</div></div><div className="shrink-0 text-right text-xs opacity-45"><div>{customer.lead_count} leads</div><div className="mt-1">{relativeAge(customer.last_activity_at||customer.created_at)}</div></div></div></button>)}</div>:<EmptyState title="No customer records" detail="Customers are created from leads and can include people who first contacted the dealership outside LoadLink."/>}<div className="flex justify-between border-t border-current/10 p-3 text-xs"><span className="opacity-45">{data.total} customers</span><div className="flex gap-2"><button disabled={data.page<=1} onClick={()=>void load(data.page-1)} className="font-black disabled:opacity-25">Previous</button><button disabled={data.page>=data.pages} onClick={()=>void load(data.page+1)} className="font-black disabled:opacity-25">Next</button></div></div></Surface>
      <Surface darkMode={darkMode} className="overflow-hidden">{selected?<><div className="border-b border-current/10 p-4 sm:p-5"><SectionHeading title={selected.name} detail={`${selected.source.replaceAll("_"," ")}${selected.phone?` · ${selected.phone}`:""}`} action={<div className="flex gap-2"><SecondaryButton darkMode={darkMode} type="button" onClick={openPrefs}>Requirements</SecondaryButton><PrimaryButton type="button" onClick={()=>setNoteOpen(true)}>Add note</PrimaryButton></div>}/><div className="mt-4 grid gap-px border border-current/10 bg-current/10 sm:grid-cols-3"><Small darkMode={darkMode} label="Leads" value={selected.lead_count}/><Small darkMode={darkMode} label="Quotes" value={selected.quote_count}/><Small darkMode={darkMode} label="Appointments" value={selected.appointment_count}/></div>{selected.preferred_make||selected.preferred_vehicle_type||selected.budget_max?<div className="mt-4 text-xs"><b>Looking for:</b> {[selected.preferred_make,selected.preferred_vehicle_type,selected.budget_max?`up to ${formatZar(selected.budget_max)}`:null].filter(Boolean).join(" · ")}</div>:null}</div>
        <div className="grid gap-0 lg:grid-cols-[1fr_260px]"><div className="border-b border-current/10 lg:border-b-0 lg:border-r"><div className="px-4 py-3 text-[10px] font-black uppercase tracking-[.1em] opacity-40">Timeline</div>{timeline.length?<div className="divide-y divide-current/10">{timeline.map(e=><div key={e.id} className="px-4 py-3"><div className="flex justify-between gap-3"><div className="text-sm font-black">{e.title}</div><time className="shrink-0 text-[10px] opacity-40">{relativeAge(e.created_at)}</time></div>{e.detail?<div className="mt-1 text-sm leading-5 opacity-55">{e.detail}</div>:null}</div>)}</div>:<EmptyState title="No activity yet" detail="Notes, calls, quotes, appointments and pipeline events will build the customer timeline."/>}</div><div><div className="px-4 py-3 text-[10px] font-black uppercase tracking-[.1em] opacity-40">Matching stock</div>{matches.length?<div className="divide-y divide-current/10">{matches.slice(0,5).map(m=><div key={m.id} className="p-3"><div className="flex gap-3">{m.photo?<img src={m.photo} alt="" className="h-12 w-16 object-cover"/>:null}<div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{m.title}</div><div className="mt-1 text-[11px] opacity-45">{formatZar(m.price_amount)}{m.match_reason?` · ${m.match_reason}`:""}</div></div></div><div className="mt-2 flex gap-3"><Link href={`/vehicles/${m.id}`} className="text-[11px] font-black underline underline-offset-4">View</Link><button type="button" onClick={()=>navigator.clipboard?.writeText(`${window.location.origin}/vehicles/${m.id}`)} className="text-[11px] font-black underline underline-offset-4">Copy link</button></div></div>)}</div>:<div className="px-4 pb-5 text-xs opacity-45">Save the customer's budget and vehicle requirements to match available stock.</div>}</div></div>
      </>:<EmptyState title="Select a customer" detail="Open a customer to see their timeline, requirements and matching dealership stock."/>}</Surface>
    </div>
    <Modal open={noteOpen} onClose={()=>setNoteOpen(false)} darkMode={darkMode} title="Add internal note"><Textarea darkMode={darkMode} value={note} onChange={e=>setNote(e.target.value)} placeholder="Only your dealership team can see this note."/><label className="mt-3 block text-xs font-black">Notify teammate<Select darkMode={darkMode} className="mt-1" value={notifyUser} onChange={e=>setNotifyUser(e.target.value)}><option value="">No notification</option>{team.filter(x=>x.user_id&&x.is_active).map(x=><option key={x.id} value={x.user_id||""}>{x.name||x.email||x.role}</option>)}</Select></label><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>void addNote()} disabled={!note.trim()}>Save note</PrimaryButton></div></Modal>
    <Modal open={prefOpen} onClose={()=>setPrefOpen(false)} darkMode={darkMode} title="Customer requirements"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">Budget from<Input darkMode={darkMode} className="mt-1" inputMode="decimal" value={prefs.budget_min} onChange={e=>setPrefs({...prefs,budget_min:e.target.value})}/></label><label className="text-xs font-black">Budget to<Input darkMode={darkMode} className="mt-1" inputMode="decimal" value={prefs.budget_max} onChange={e=>setPrefs({...prefs,budget_max:e.target.value})}/></label><label className="text-xs font-black">Preferred make<Input darkMode={darkMode} className="mt-1" value={prefs.preferred_make} onChange={e=>setPrefs({...prefs,preferred_make:e.target.value})}/></label><label className="text-xs font-black">Vehicle type<Input darkMode={darkMode} className="mt-1" value={prefs.preferred_vehicle_type} onChange={e=>setPrefs({...prefs,preferred_vehicle_type:e.target.value})}/></label><label className="text-xs font-black sm:col-span-2">Other preferences<Input darkMode={darkMode} className="mt-1" value={prefs.preferences} onChange={e=>setPrefs({...prefs,preferences:e.target.value})} placeholder="Automatic, 6x4, sleeper cab"/></label></div><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>void savePrefs()}>Save requirements</PrimaryButton></div></Modal>
  </div>;
}
function Small({darkMode,label,value}:{darkMode:boolean;label:string;value:string|number}){return <div className={`${darkMode?"bg-[#0d0d0d]":"bg-[#fbfaf6]"} p-3`}><div className="text-[9px] font-black uppercase tracking-[.1em] opacity-40">{label}</div><div className="mt-1 text-lg font-black">{value}</div></div>}
