"use client";

import { useEffect, useState } from "react";
import { dealerFetch } from "@/lib/dealer/client";
import type { DealerCampaign, DealerInventoryItem } from "@/lib/dealer/types";
import { EmptyState, Input, Modal, PrimaryButton, SectionHeading, Select, SecondaryButton, Surface } from "./ui";

export default function DealerCampaigns({ darkMode, inventory }: { darkMode: boolean; inventory: DealerInventoryItem[] }) {
  const [items, setItems] = useState<DealerCampaign[]>([]);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: "", campaign_type: "slow_stock", listing_ids: [] as string[], starts_at: "", ends_at: "", discount_percent: "10" });

  async function load() { try { const data = await dealerFetch<{ items: DealerCampaign[] }>("/api/dealer/campaigns"); setItems(data.items || []); } catch { setItems([]); } }
  useEffect(() => { void load(); }, []);
  async function create() { await dealerFetch("/api/dealer/campaigns", { method: "POST", body: JSON.stringify({ action: "create", ...form }) }); setOpen(false); setForm({ title: "", campaign_type: "slow_stock", listing_ids: [], starts_at: "", ends_at: "", discount_percent: "10" }); await load(); }

  async function cancel(campaign_id: string) { await dealerFetch("/api/dealer/campaigns", { method: "POST", body: JSON.stringify({ action: "cancel", campaign_id }) }); await load(); }

  return <Surface darkMode={darkMode} className="overflow-hidden"><div className="border-b border-current/10 px-4 py-4 sm:px-5"><SectionHeading title="Campaigns" detail="Create controlled promotions around real dealership stock." action={<PrimaryButton type="button" onClick={() => setOpen(true)}>New campaign</PrimaryButton>} /></div>{items.length ? <div className="divide-y divide-current/10">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-4 py-4 sm:px-5"><div><div className="text-sm font-black">{item.title}</div><div className="mt-1 text-xs opacity-50">{item.campaign_type.replaceAll("_", " ")} · {item.listing_ids.length} vehicles · {item.status}</div></div><div className="flex items-center gap-3"><div className="text-right text-xs opacity-50">{item.views} views<br />{item.leads} leads</div>{["active","scheduled","draft"].includes(item.status) ? <button type="button" onClick={() => void cancel(item.id)} className="text-xs font-black underline">Cancel</button> : null}</div></div>)}</div> : <EmptyState title="No campaigns yet" detail="Use campaigns for new arrivals, slow stock, price drops and weekend promotions." />}
    <Modal open={open} onClose={() => setOpen(false)} darkMode={darkMode} title="New campaign"><div className="grid gap-3"><label className="text-xs font-black">Campaign name<Input darkMode={darkMode} className="mt-1" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="text-xs font-black">Goal<Select darkMode={darkMode} className="mt-1" value={form.campaign_type} onChange={(e) => setForm({ ...form, campaign_type: e.target.value })}><option value="slow_stock">Move slow stock</option><option value="new_arrivals">New arrivals</option><option value="price_drop">Price drop</option><option value="weekend">Weekend promotion</option><option value="showroom">Drive showroom enquiries</option></Select></label><div className="max-h-48 overflow-y-auto border border-current/10 p-2">{inventory.filter((item) => item.stock_status === "available").map((item) => <label key={item.id} className="flex items-center gap-2 px-2 py-2 text-sm"><input type="checkbox" checked={form.listing_ids.includes(item.id)} onChange={(e) => setForm({ ...form, listing_ids: e.target.checked ? [...form.listing_ids, item.id] : form.listing_ids.filter((id) => id !== item.id) })} /><span>{item.title}</span></label>)}</div>{form.campaign_type === "price_drop" ? <label className="text-xs font-black">Price drop %<Input darkMode={darkMode} className="mt-1" type="number" min="1" max="50" value={form.discount_percent} onChange={(e) => setForm({ ...form, discount_percent: e.target.value })} /></label> : null}<div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">Starts<Input darkMode={darkMode} className="mt-1" type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} /></label><label className="text-xs font-black">Ends<Input darkMode={darkMode} className="mt-1" type="datetime-local" value={form.ends_at} onChange={(e) => setForm({ ...form, ends_at: e.target.value })} /></label></div></div><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={create} disabled={!form.title.trim() || !form.listing_ids.length}>Create campaign</PrimaryButton></div></Modal>
  </Surface>;
}
