"use client";

import { useState, type ReactNode } from "react";
import AuthStatusButton from "@/components/AuthStatusButton";
import HomeLogoLink from "@/components/HomeLogoLink";
import LoadLinkThemeToggle from "@/components/LoadLinkThemeToggle";
import SiteMenu from "@/components/SiteMenu";
import type { DealerProfile, DealerSection, DealerWorkspaceState } from "@/lib/dealer/types";
import DealerGlobalSearch from "./DealerGlobalSearch";

const sectionPermission: Partial<Record<DealerSection, string>> = {
  inventory:"inventory.read",leads:"leads.read",customers:"customers.read",messages:"messages.read",analytics:"analytics.read",marketing:"marketing.read",team:"team.read",showroom:"showroom.read",verification:"verification.read",billing:"billing.read",reviews:"reviews.read",activity:"activity.read",settings:"showroom.write",
};
const CORE:Array<{id:DealerSection;label:string}>=[{id:"overview",label:"Home"},{id:"inventory",label:"Stock"},{id:"leads",label:"Sales"},{id:"messages",label:"Inbox"}];
const MORE:Array<{id:DealerSection;label:string;group:string}>=[
  {id:"showroom",label:"Dealer page",group:"Dealership"},{id:"marketing",label:"Status & updates",group:"Dealership"},{id:"customers",label:"Customers",group:"Sales"},{id:"analytics",label:"Performance",group:"Sales"},{id:"reviews",label:"Reviews",group:"Sales"},{id:"team",label:"Team",group:"Business"},{id:"activity",label:"Activity",group:"Business"},{id:"verification",label:"Verification",group:"Account"},{id:"billing",label:"Billing",group:"Account"},{id:"settings",label:"Settings",group:"Account"},{id:"support",label:"Support",group:"Account"},
];
function statusText(c:DealerWorkspaceState){if(c.account_status==="blocked")return"Account blocked";if(c.account_status==="suspended")return"Account suspended";if(c.subscription_status==="past_due")return"Payment attention required";if(c.verification_status==="changes_required")return"Verification needs attention";if(c.verification_status!=="approved")return"Setup in progress";return c.showroom_status==="live"?"Live on LoadLink":"Ready to publish";}

export default function DealerShell({darkMode,toggleTheme,profile,context,section,setSection,onAddVehicle,children}:{darkMode:boolean;toggleTheme:()=>void;profile:DealerProfile;context:DealerWorkspaceState;section:DealerSection;setSection:(section:DealerSection)=>void;onAddVehicle:()=>void;children:ReactNode}){
  const [moreOpen,setMoreOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false);
  const can=(id:DealerSection)=>{const p=sectionPermission[id];return !p||context.permissions.includes(p as never)}; const core=CORE.filter(i=>can(i.id)); const more=MORE.filter(i=>can(i.id)); const moreActive=more.some(i=>i.id===section);
  const go=(next:DealerSection)=>{setSection(next);setMoreOpen(false);setSearchOpen(false)};
  const groups=["Dealership","Sales","Business","Account"];

  return <main className={`min-h-screen ${darkMode?"bg-black text-white":"bg-[#f4f0e7] text-black"}`} data-loadlink-dealer-control-centre="simple-v2">
    <header className={`sticky top-0 z-50 h-[62px] border-b backdrop-blur-xl ${darkMode?"border-white/10 bg-black/92":"border-black/10 bg-[#f7f4ec]/95"}`}><div className="relative mx-auto flex h-full max-w-[1460px] items-center px-3 sm:px-5"><div className="flex items-center gap-1"><SiteMenu darkMode={darkMode}/><AuthStatusButton darkMode={darkMode}/></div><div className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><div className="pointer-events-auto"><HomeLogoLink className="w-[102px] sm:w-[114px]"/></div></div><div className="ml-auto"><LoadLinkThemeToggle darkMode={darkMode} onToggle={toggleTheme}/></div></div></header>

    <div className="mx-auto max-w-[1460px] px-3 pb-24 pt-3 sm:px-5 lg:grid lg:grid-cols-[176px_minmax(0,1fr)] lg:gap-4 lg:pb-10 lg:pt-5">
      <aside className={`hidden h-[calc(100vh-82px)] self-start rounded-2xl border lg:sticky lg:top-[74px] lg:block ${darkMode?"border-white/10 bg-[#0b0b0b]":"border-black/[.08] bg-white"}`}>
        <div className="flex items-center gap-2.5 border-b border-current/10 p-3"><Avatar darkMode={darkMode} profile={profile}/><div className="min-w-0"><div className="truncate text-[12px] font-black">{profile.name}</div><div className="mt-0.5 flex items-center gap-1.5 truncate text-[9px] font-semibold opacity-45"><Dot context={context}/>{statusText(context)}</div></div></div>
        <nav className="p-2">{core.map(i=><Side key={i.id} active={section===i.id} onClick={()=>go(i.id)}>{i.label}</Side>)}<button type="button" onClick={()=>setMoreOpen(v=>!v)} className={`mt-1 flex min-h-9 w-full items-center justify-between rounded-lg px-3 text-left text-[12px] font-black ${moreActive?"bg-current/[.07]":"opacity-55 hover:bg-current/[.04]"}`}><span>More</span><span className="opacity-35">{moreOpen||moreActive?"−":"+"}</span></button>{moreOpen||moreActive?<div className="mt-2 max-h-[calc(100vh-310px)] overflow-y-auto border-t border-current/10 pt-1">{groups.map(group=>{const items=more.filter(i=>i.group===group);if(!items.length)return null;return <div key={group} className="mb-1"><div className="px-3 pb-1 pt-2 text-[8px] font-black uppercase tracking-[.1em] opacity-25">{group}</div>{items.map(i=><Side key={i.id} active={section===i.id} onClick={()=>go(i.id)}>{i.label}</Side>)}</div>})}</div>:null}</nav>
      </aside>

      <div className="min-w-0"><div className={`mb-3 rounded-2xl border px-3 py-2.5 ${darkMode?"border-white/10 bg-[#0c0c0c]":"border-black/[.08] bg-white"}`}><div className="flex items-center gap-2"><div className="lg:hidden"><Avatar darkMode={darkMode} profile={profile}/></div><div className="min-w-0 flex-1 lg:hidden"><div className="truncate text-[14px] font-black">{profile.name}</div><div className="mt-0.5 flex items-center gap-1.5 truncate text-[9px] opacity-45"><Dot context={context}/>{statusText(context)}</div></div><div className="hidden flex-1 text-[10px] font-black uppercase tracking-[.1em] opacity-30 lg:block">Dealer workspace</div><button type="button" onClick={()=>setSearchOpen(v=>!v)} className={`h-9 rounded-lg border px-3 text-[10px] font-black ${darkMode?"border-white/10":"border-black/10"}`}>Search</button><button type="button" onClick={onAddVehicle} className="h-9 rounded-lg bg-[#f6b800] px-3 text-[10px] font-black text-black">Add vehicle</button></div>{searchOpen?<div className="mt-2"><DealerGlobalSearch darkMode={darkMode} setSection={go}/></div>:null}</div>{children}</div>
    </div>

    <nav className={`fixed inset-x-0 bottom-0 z-50 border-t px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-1.5 backdrop-blur-xl lg:hidden ${darkMode?"border-white/10 bg-[#080808]/96":"border-black/10 bg-white/96"}`}><div className="mx-auto grid max-w-xl grid-cols-5 gap-1">{core.map(i=><Mobile key={i.id} active={section===i.id} onClick={()=>go(i.id)}>{i.label}</Mobile>)}<div className="relative"><Mobile active={moreActive} onClick={()=>setMoreOpen(v=>!v)}>More</Mobile>{moreOpen?<div className={`absolute bottom-[58px] right-0 w-[238px] max-h-[62vh] overflow-y-auto rounded-2xl border p-2 shadow-2xl ${darkMode?"border-white/10 bg-[#111]":"border-black/10 bg-white"}`}>{groups.map(group=>{const items=more.filter(i=>i.group===group);if(!items.length)return null;return <div key={group}><div className="px-3 pb-1 pt-2 text-[8px] font-black uppercase tracking-[.1em] opacity-25">{group}</div>{items.map(i=><button type="button" key={i.id} onClick={()=>go(i.id)} className={`mb-0.5 min-h-10 w-full rounded-lg px-3 text-left text-xs font-black ${section===i.id?"bg-current/[.08]":"opacity-60"}`}>{i.label}</button>)}</div>})}</div>:null}</div></div></nav>
  </main>;
}
function Avatar({darkMode,profile}:{darkMode:boolean;profile:DealerProfile}){return <div className={`h-9 w-9 shrink-0 overflow-hidden rounded-full border ${darkMode?"border-white/10 bg-white/[.04]":"border-black/10 bg-[#f7f4ec]"}`}>{profile.profile_image_url?<img src={profile.profile_image_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[9px] font-black">{profile.name.slice(0,2).toUpperCase()}</div>}</div>}
function Dot({context}:{context:DealerWorkspaceState}){return <span className={`h-1.5 w-1.5 shrink-0 rounded-full ${context.showroom_status==="live"&&context.subscription_status==="active"?"bg-emerald-500":"bg-[#f6b800]"}`}/>}
function Side({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} className={`mb-0.5 flex min-h-9 w-full items-center rounded-lg px-3 text-left text-[12px] font-black ${active?"bg-current/[.08]":"opacity-55 hover:bg-current/[.04] hover:opacity-100"}`}>{children}</button>}
function Mobile({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} className={`min-h-[48px] rounded-lg px-1 text-[10px] font-black ${active?"bg-current/[.08]":"opacity-45"}`}>{children}</button>}
