"use client";

import { useEffect, useState } from "react";
import { dealerFetch, formatZar } from "@/lib/dealer/client";
import type { DealerBilling as BillingType, DealerWorkspaceState } from "@/lib/dealer/types";
import { EmptyState, PrimaryButton, SectionHeading, SecondaryButton, Surface } from "./ui";

export default function DealerBilling({ darkMode, context }: { darkMode: boolean; context: DealerWorkspaceState }) {
  const [billing, setBilling] = useState<BillingType | null>(null);
  const [message, setMessage] = useState("");
  async function load() { try { setBilling(await dealerFetch<BillingType>("/api/dealer/billing")); } catch { setBilling(null); } }
  useEffect(() => { void load(); }, []);
  async function action(name: string) { setMessage(""); try { const r = await dealerFetch<{ message?: string }>("/api/dealer/billing", { method: "POST", body: JSON.stringify({ action: name }) }); setMessage(r.message || "Billing updated."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Billing could not be updated."); } }

  return <div className="grid gap-4"><Surface darkMode={darkMode} className="p-4 sm:p-5"><SectionHeading title="Billing" detail="Dealer subscription, renewal state and invoices in one place." /><div className="mt-5 grid gap-px overflow-hidden border border-current/10 bg-current/10 sm:grid-cols-4"><Box darkMode={darkMode} label="Plan" value="Dealer" /><Box darkMode={darkMode} label="Monthly" value="R2,999" /><Box darkMode={darkMode} label="Status" value={context.subscription_status.replaceAll("_", " ")} /><Box darkMode={darkMode} label="Renews" value={context.renewal_at ? new Date(context.renewal_at).toLocaleDateString("en-ZA") : "—"} /></div>{context.subscription_status === "past_due" || context.subscription_status === "grace_period" ? <div className="mt-4 border-l-2 border-[#f6b800] pl-4 text-sm"><b>Payment attention required.</b><p className="mt-1 opacity-60">Your dealership data is safe. Resolve payment before the grace period ends to keep the showroom public.</p></div> : null}{message ? <div className="mt-3 text-sm font-bold">{message}</div> : null}<div className="mt-5 flex flex-wrap gap-2">{["past_due", "grace_period", "expired"].includes(context.subscription_status) ? <PrimaryButton type="button" onClick={() => action("resolve")}>Resolve payment</PrimaryButton> : null}<SecondaryButton darkMode={darkMode} type="button" onClick={() => action("cancel")}>Manage renewal</SecondaryButton></div></Surface><Surface darkMode={darkMode} className="overflow-hidden"><div className="border-b border-current/10 px-4 py-4 sm:px-5"><SectionHeading title="Invoices" /></div>{billing?.invoices?.length ? <div className="divide-y divide-current/10">{billing.invoices.map((invoice) => <div key={invoice.id} className="flex items-center justify-between gap-4 px-4 py-4 sm:px-5"><div><div className="text-sm font-black">{invoice.invoice_number}</div><div className="mt-1 text-xs opacity-50">{new Date(invoice.issued_at).toLocaleDateString("en-ZA")} · {invoice.status}</div></div><div className="text-right"><div className="text-sm font-black">{formatZar(invoice.amount_cents / 100)}</div><a href={`/api/dealer/billing?invoice=${invoice.id}`} target="_blank" className="mt-1 block text-xs font-black">Open invoice</a></div></div>)}</div> : <EmptyState title="No invoices yet" detail="Dealer invoices will appear here after billing events are recorded." />}</Surface></div>;
}
function Box({ darkMode, label, value }: { darkMode: boolean; label: string; value: string }) { return <div className={`${darkMode ? "bg-[#101010]" : "bg-white"} p-4`}><div className="text-[10px] font-black uppercase tracking-[.1em] opacity-40">{label}</div><div className="mt-2 text-sm font-black capitalize">{value}</div></div>; }
