"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { dealerFetch, formatZar } from "@/lib/dealer/client";
import type { DealerInventoryItem, DealerWorkspaceState } from "@/lib/dealer/types";
import DealerBulkImport from "./DealerBulkImport";
import { EmptyState, Input, Modal, PrimaryButton, SectionHeading, Select, SecondaryButton, Surface } from "./ui";

type InventoryResponse={items:DealerInventoryItem[];total:number;page:number;page_size:number;pages:number};
type ModalState={type:"price"|"sold"|"duplicate"|"stock_number";item:DealerInventoryItem}|null;
const SOURCES=["loadlink","whatsapp","phone","walk_in","website","facebook","instagram","referral","repeat_customer","other"];

export default function DealerInventory({darkMode,context,onAddVehicle}:{darkMode:boolean;context:DealerWorkspaceState;onAddVehicle:()=>void}){
  const [data,setData]=useState<InventoryResponse>({items:[],total:0,page:1,page_size:20,pages:1}); const [query,setQuery]=useState(""); const [stock,setStock]=useState("all"); const [publication,setPublication]=useState("all"); const [moderation,setModeration]=useState("all"); const [sort,setSort]=useState("newest"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [bulkOpen,setBulkOpen]=useState(false); const [modal,setModal]=useState<ModalState>(null); const [price,setPrice]=useState(""); const [saleSource,setSaleSource]=useState("loadlink"); const [salePrice,setSalePrice]=useState(""); const [stockNumber,setStockNumber]=useState("");
  async function load(page=1){setLoading(true);setError("");try{const r=await dealerFetch<InventoryResponse>(`/api/dealer/inventory?${new URLSearchParams({page:String(page),page_size:"20",q:query,stock,publication,moderation,sort})}`);setData(r);setSelected([])}catch(e){setError(e instanceof Error?e.message:"Inventory could not be loaded.")}finally{setLoading(false)}}
  useEffect(()=>{const t=setTimeout(()=>void load(1),220);return()=>clearTimeout(t)},[query,stock,publication,moderation,sort]);
  async function basic(action:string,ids:string[],value?:string){setError("");try{await dealerFetch("/api/dealer/inventory",{method:"POST",body:JSON.stringify({action,listing_ids:ids,value})});await load(data.page)}catch(e){setError(e instanceof Error?e.message:"Stock could not be updated.")}}
  async function command(action:string,payload:Record<string,unknown>){setError("");try{const r=await dealerFetch<{listing_id?:string}>("/api/dealer/inventory",{method:"POST",body:JSON.stringify({action,...payload})});setModal(null);await load(data.page);if(action==="duplicate"&&r.listing_id) window.location.assign(`/my-posts`)}catch(e){setError(e instanceof Error?e.message:"Stock could not be updated.")}}
  async function share(item:DealerInventoryItem){const url=`${window.location.origin}/vehicles/${item.id}`; if(navigator.share){try{await navigator.share({title:item.title,url});return}catch{}} await navigator.clipboard?.writeText(url)}
  function open(type:NonNullable<ModalState>["type"],item:DealerInventoryItem){setModal({type,item});setPrice(item.price_amount?String(item.price_amount):"");setSalePrice(item.price_amount?String(item.price_amount):"");setSaleSource("loadlink");setStockNumber(item.stock_number||"")}
  const allSelected=useMemo(()=>data.items.length>0&&data.items.every(i=>selected.includes(i.id)),[data.items,selected]);
  return <div className="grid gap-4">
    <Surface darkMode={darkMode} className="p-4 sm:p-5"><SectionHeading title="Inventory" detail="Stock, publishing, LoadLink review and performance stay separate so each vehicle's state is clear." action={<div className="hidden gap-2 sm:flex"><SecondaryButton darkMode={darkMode} type="button" onClick={()=>setBulkOpen(true)} disabled={!context.permissions.includes("inventory.bulk")}>Import stock</SecondaryButton><PrimaryButton type="button" onClick={onAddVehicle}>Add vehicle</PrimaryButton></div>}/><div className="mt-5 grid gap-2 md:grid-cols-[minmax(220px,1fr)_150px_150px_160px_150px]"><Input darkMode={darkMode} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stock number, make, model or title"/><Select darkMode={darkMode} value={stock} onChange={e=>setStock(e.target.value)}><option value="all">All stock</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option></Select><Select darkMode={darkMode} value={publication} onChange={e=>setPublication(e.target.value)}><option value="all">All publishing</option><option value="draft">Draft</option><option value="live">Live</option><option value="paused">Paused</option><option value="expired">Expired</option><option value="archived">Archived</option></Select><Select darkMode={darkMode} value={moderation} onChange={e=>setModeration(e.target.value)}><option value="all">All review states</option><option value="pending">Pending review</option><option value="approved">Approved</option><option value="changes_required">Changes required</option><option value="rejected">Rejected</option></Select><Select darkMode={darkMode} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="age_desc">Oldest stock</option><option value="views_desc">Most viewed</option><option value="leads_desc">Most leads</option></Select></div><div className="mt-3 flex gap-2 sm:hidden"><SecondaryButton darkMode={darkMode} type="button" className="flex-1" onClick={()=>setBulkOpen(true)}>Import</SecondaryButton><PrimaryButton type="button" className="flex-1" onClick={onAddVehicle}>Add vehicle</PrimaryButton></div>{error?<div className="mt-3 text-sm font-bold text-red-500">{error}</div>:null}</Surface>
    {selected.length?<Surface darkMode={darkMode} className="flex flex-wrap items-center gap-2 p-3"><span className="mr-auto text-sm font-black">{selected.length} selected</span><SecondaryButton darkMode={darkMode} type="button" onClick={()=>void basic("stock",selected,"available")}>Available</SecondaryButton><SecondaryButton darkMode={darkMode} type="button" onClick={()=>void basic("stock",selected,"reserved")}>Reserved</SecondaryButton><SecondaryButton darkMode={darkMode} type="button" onClick={()=>void basic("publication",selected,"paused")}>Pause</SecondaryButton><SecondaryButton darkMode={darkMode} type="button" onClick={()=>void basic("publication",selected,"archived")}>Archive</SecondaryButton></Surface>:null}
    <Surface darkMode={darkMode} className="overflow-hidden">{loading?<div className="px-5 py-14 text-center text-sm font-bold opacity-45">Loading inventory…</div>:!data.items.length?<EmptyState title="No stock found" detail="Add a vehicle or change the filters." action={<PrimaryButton type="button" onClick={onAddVehicle}>Add vehicle</PrimaryButton>}/>:<><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-current/10 text-[10px] uppercase tracking-[.1em] opacity-45"><tr><th className="px-4 py-3"><input type="checkbox" checked={allSelected} onChange={e=>setSelected(e.target.checked?data.items.map(i=>i.id):[])}/></th><th className="px-2 py-3">Vehicle</th><th className="px-2 py-3">Stock</th><th className="px-2 py-3">Publishing</th><th className="px-2 py-3">LoadLink review</th><th className="px-2 py-3">Performance</th><th className="px-2 py-3">Age</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-current/10">{data.items.map(item=><Row key={item.id} item={item} darkMode={darkMode} selected={selected.includes(item.id)} toggle={()=>setSelected(c=>c.includes(item.id)?c.filter(id=>id!==item.id):[...c,item.id])} basic={basic} open={open} share={share}/>)}</tbody></table></div><div className="divide-y divide-current/10 lg:hidden">{data.items.map(item=><Card key={item.id} item={item} darkMode={darkMode} basic={basic} open={open} share={share}/>)}</div></>}
      <div className="flex items-center justify-between border-t border-current/10 px-4 py-3 text-sm"><span className="opacity-45">{data.total} vehicles</span><div className="flex gap-2"><SecondaryButton darkMode={darkMode} type="button" disabled={data.page<=1} onClick={()=>void load(data.page-1)}>Previous</SecondaryButton><SecondaryButton darkMode={darkMode} type="button" disabled={data.page>=data.pages} onClick={()=>void load(data.page+1)}>Next</SecondaryButton></div></div></Surface>
    <DealerBulkImport darkMode={darkMode} open={bulkOpen} onClose={()=>setBulkOpen(false)} onDone={()=>void load(1)}/>
    <Modal open={modal?.type==="price"} onClose={()=>setModal(null)} darkMode={darkMode} title="Change vehicle price"><p className="text-sm opacity-55">A price change on an approved listing returns the vehicle to LoadLink review before it goes live again.</p><label className="mt-4 block text-xs font-black">New price<Input darkMode={darkMode} className="mt-1" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>modal&&void command("price",{listing_id:modal.item.id,price_amount:price})}>Save price</PrimaryButton></div></Modal>
    <Modal open={modal?.type==="sold"} onClose={()=>setModal(null)} darkMode={darkMode} title="Mark vehicle sold"><p className="text-sm opacity-55">The vehicle will leave public search immediately. Recording the source keeps sales reports useful.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">Sale source<Select darkMode={darkMode} className="mt-1" value={saleSource} onChange={e=>setSaleSource(e.target.value)}>{SOURCES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select></label><label className="text-xs font-black">Sale price (optional)<Input darkMode={darkMode} className="mt-1" inputMode="decimal" value={salePrice} onChange={e=>setSalePrice(e.target.value)}/></label></div><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>modal&&void command("sold",{listing_id:modal.item.id,source:saleSource,sale_price:salePrice||null})}>Mark sold</PrimaryButton></div></Modal>
    <Modal open={modal?.type==="stock_number"} onClose={()=>setModal(null)} darkMode={darkMode} title="Stock number"><label className="block text-xs font-black">Dealer stock number<Input darkMode={darkMode} className="mt-1" value={stockNumber} maxLength={40} onChange={e=>setStockNumber(e.target.value)} placeholder="e.g. PTA-2048"/></label><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>modal&&void command("stock_number",{listing_id:modal.item.id,stock_number:stockNumber})}>Save</PrimaryButton></div></Modal>
    <Modal open={modal?.type==="duplicate"} onClose={()=>setModal(null)} darkMode={darkMode} title="Duplicate as draft"><p className="text-sm opacity-55">A copy is created as a private draft and must be reviewed before it can be published. Use this for similar stock, not the same vehicle.</p><div className="mt-5 flex justify-end"><PrimaryButton type="button" onClick={()=>modal&&void command("duplicate",{listing_id:modal.item.id})}>Create draft copy</PrimaryButton></div></Modal>
  </div>
}

function Row({item,darkMode,selected,toggle,basic,open,share}:{item:DealerInventoryItem;darkMode:boolean;selected:boolean;toggle:()=>void;basic:(a:string,ids:string[],v?:string)=>Promise<void>;open:(t:NonNullable<ModalState>["type"],i:DealerInventoryItem)=>void;share:(i:DealerInventoryItem)=>Promise<void>}){const photo=item.photos?.[0];return <tr><td className="px-4 py-3"><input type="checkbox" checked={selected} onChange={toggle}/></td><td className="px-2 py-3"><div className="flex items-center gap-3"><div className={`h-12 w-16 overflow-hidden border ${darkMode?"border-white/10 bg-white/[.04]":"border-black/10 bg-[#f5f2eb]"}`}>{photo?<img src={photo} alt="" className="h-full w-full object-cover"/>:null}</div><div className="min-w-0"><div className="max-w-[280px] truncate font-black">{item.title}</div><div className="mt-1 text-xs opacity-50">{item.stock_number?`${item.stock_number} · `:""}{formatZar(item.price_amount)} · {item.city}</div>{item.missing_fields.length?<div className="mt-1 text-[10px] font-bold text-amber-600">Missing: {item.missing_fields.slice(0,3).join(", ")}</div>:null}</div></div></td><td className="px-2 py-3 capitalize">{item.stock_status}</td><td className="px-2 py-3 capitalize">{item.lifecycle_status}</td><td className="px-2 py-3"><span className={item.moderation_status==="approved"?"text-emerald-600":item.moderation_status==="rejected"||item.moderation_status==="changes_required"?"text-red-500":"opacity-60"}>{item.moderation_status.replaceAll("_"," ")}</span></td><td className="px-2 py-3 text-xs"><div>{item.views.toLocaleString()} views</div><div className="mt-1 opacity-50">{item.leads} leads · {item.saves} saves</div></td><td className="px-2 py-3">{item.days_in_stock}d</td><td className="px-4 py-3"><Actions item={item} darkMode={darkMode} basic={basic} open={open} share={share}/></td></tr>}
function Card({item,darkMode,basic,open,share}:{item:DealerInventoryItem;darkMode:boolean;basic:(a:string,ids:string[],v?:string)=>Promise<void>;open:(t:NonNullable<ModalState>["type"],i:DealerInventoryItem)=>void;share:(i:DealerInventoryItem)=>Promise<void>}){return <article className="p-4"><div className="flex gap-3"><div className={`h-20 w-24 shrink-0 overflow-hidden border ${darkMode?"border-white/10 bg-white/[.04]":"border-black/10 bg-[#f5f2eb]"}`}>{item.photos?.[0]?<img src={item.photos[0]} alt="" className="h-full w-full object-cover"/>:null}</div><div className="min-w-0 flex-1"><div className="font-black">{item.title}</div><div className="mt-1 text-sm opacity-55">{formatZar(item.price_amount)} · {item.city}</div>{item.stock_number?<div className="mt-1 text-[11px] opacity-40">Stock {item.stock_number}</div>:null}<div className="mt-2 flex flex-wrap gap-2 text-[10px] font-black uppercase"><span>{item.stock_status}</span><span className="opacity-35">•</span><span>{item.lifecycle_status}</span><span className="opacity-35">•</span><span>{item.moderation_status.replaceAll("_"," ")}</span></div></div></div><div className="mt-3 grid grid-cols-4 gap-px border border-current/10 bg-current/10 text-center text-xs">{[[item.views,"views"],[item.leads,"leads"],[item.saves,"saves"],[`${item.days_in_stock}d`,"age"]].map(([v,l])=><div key={String(l)} className={`${darkMode?"bg-[#111]":"bg-white"} p-2`}><b>{v}</b><span className="block opacity-45">{l}</span></div>)}</div>{item.missing_fields.length?<div className="mt-3 border-l-2 border-[#f6b800] pl-3 text-xs"><b>Needs attention:</b> {item.missing_fields.join(", ")}</div>:null}<div className="mt-3"><Actions item={item} darkMode={darkMode} basic={basic} open={open} share={share}/></div></article>}
function Actions({item,darkMode,basic,open,share}:{item:DealerInventoryItem;darkMode:boolean;basic:(a:string,ids:string[],v?:string)=>Promise<void>;open:(t:NonNullable<ModalState>["type"],i:DealerInventoryItem)=>void;share:(i:DealerInventoryItem)=>Promise<void>}){return <div className="flex flex-wrap justify-end gap-2"><Link href={`/vehicles/${item.id}`} className={`flex min-h-9 items-center border px-3 text-[11px] font-black ${darkMode?"border-white/12":"border-black/10"}`}>View</Link><button type="button" onClick={()=>void share(item)} className="min-h-9 px-2 text-[11px] font-black opacity-60 hover:opacity-100">Share</button><Link href={`/dealer/brochure/${item.id}`} className="min-h-9 px-2 py-2 text-[11px] font-black opacity-60 hover:opacity-100">Vehicle sheet</Link><select defaultValue="" aria-label={`Manage ${item.title}`} onChange={e=>{const v=e.target.value;e.currentTarget.value="";if(v==="price"||v==="sold"||v==="duplicate"||v==="stock_number")open(v,item);else if(v.startsWith("stock:"))void basic("stock",[item.id],v.split(":")[1]);else if(v.startsWith("pub:"))void basic("publication",[item.id],v.split(":")[1]);else if(v==="manage")window.location.assign("/my-posts")}} className={`h-9 border px-2 text-[11px] font-black outline-none ${darkMode?"border-white/12 bg-[#151515]":"border-black/10 bg-white"}`}><option value="">Manage</option><option value="price">Change price</option><option value="stock_number">Stock number</option><option value="stock:available">Mark available</option><option value="stock:reserved">Mark reserved</option><option value="sold">Mark sold</option><option value={item.lifecycle_status==="live"?"pub:paused":"pub:live"}>{item.lifecycle_status==="live"?"Pause":"Publish"}</option><option value="duplicate">Duplicate as draft</option><option value="manage">Full edit in My Posts</option><option value="pub:archived">Archive</option></select></div>}
