"use client";

import { useEffect, useMemo, useState } from "react";
import type { DealerAnalytics, DealerAppointment, DealerInsight, DealerLead, DealerSection, DealerSummary, DealerWorkspaceState } from "@/lib/dealer/types";
import { dealerFetch, relativeAge } from "@/lib/dealer/client";
import DealerIntelligencePanel from "./DealerIntelligencePanel";
import { EmptyState, Metric, SectionHeading, Surface } from "./ui";

const EMPTY_WEEK:DealerAnalytics={range_days:7,totals:{showroom_views:0,vehicle_views:0,search_appearances:0,saves:0,enquiries:0,leads:0,won:0,response_rate:0,avg_response_minutes:null,followers_gained:0},lead_sources:[],stock_performance:[],salesperson_performance:[],daily:[]};
export default function DealerOverview({darkMode,context,summary,leads,appointments,insights,setSection}:{darkMode:boolean;context:DealerWorkspaceState;summary:DealerSummary;leads:DealerLead[];appointments:DealerAppointment[];insights:DealerInsight[];setSection:(section:DealerSection)=>void}){
  const [week,setWeek]=useState<DealerAnalytics>(EMPTY_WEEK); useEffect(()=>{void dealerFetch<DealerAnalytics>("/api/dealer/analytics?days=7").then(setWeek).catch(()=>{})},[]);
  const salesRole=context.role==="sales_agent"; const today=new Date().toLocaleDateString("en-ZA",{weekday:"long",day:"numeric",month:"long"}); const highLeads=leads.filter(l=>l.priority==="high"&&!["won","lost"].includes(l.status)); const overdue=leads.filter(l=>l.next_follow_up_at&&new Date(l.next_follow_up_at).getTime()<Date.now()&&!["won","lost"].includes(l.status));
  const health=useMemo(()=>[
    {label:"Inventory quality",detail:insights.filter(i=>i.kind==="inventory").length?`${insights.filter(i=>i.kind==="inventory").length} need attention`:"Good",section:"inventory" as DealerSection},
    {label:"Lead response",detail:summary.overdue_followups?`${summary.overdue_followups} overdue`:summary.response_rate?`${Math.round(summary.response_rate)}% response rate`:"Building history",section:"leads" as DealerSection},
    {label:"Showroom",detail:context.showroom_status==="live"?"Live":context.showroom_status.replaceAll("_"," "),section:"showroom" as DealerSection},
    {label:"Verification",detail:context.verification_status.replaceAll("_"," "),section:"verification" as DealerSection},
    {label:"Billing",detail:context.subscription_status.replaceAll("_"," "),section:"billing" as DealerSection},
    {label:"Marketing",detail:summary.active_statuses?`${summary.active_statuses} Status live`:"No active Status",section:"marketing" as DealerSection},
  ],[insights,summary,context]);
  return <div className="grid gap-4">
    <Surface darkMode={darkMode} className="p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.1em] opacity-40">{today}</div><h2 className="mt-1 text-[22px] font-black tracking-[-.035em]">{salesRole?"My day":"Dealer overview"}</h2></div><button type="button" onClick={()=>setSection("leads")} className="text-sm font-black">Open sales pipeline →</button></div><div className="mt-5 grid grid-cols-2 gap-px border border-current/10 bg-current/10 lg:grid-cols-6"><Metric darkMode={darkMode} label="Live stock" value={summary.live_stock}/><Metric darkMode={darkMode} label="New leads" value={summary.new_leads} attention={summary.new_leads>0}/><Metric darkMode={darkMode} label="Follow-ups" value={summary.overdue_followups} attention={summary.overdue_followups>0}/><Metric darkMode={darkMode} label="Unread chats" value={summary.unread_messages} attention={summary.unread_messages>0}/><Metric darkMode={darkMode} label="Viewings today" value={summary.appointments_today}/><Metric darkMode={darkMode} label="Response rate" value={`${Math.round(summary.response_rate||0)}%`}/></div></Surface>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><DealerIntelligencePanel darkMode={darkMode} insights={insights} setSection={setSection}/><Surface darkMode={darkMode} className="overflow-hidden"><div className="border-b border-current/10 px-4 py-4 sm:px-5"><SectionHeading title={salesRole?"My priorities":"Today"} detail="Closest appointments and follow-ups."/></div>{appointments.length||leads.length?<div className="divide-y divide-current/10">{appointments.slice(0,3).map(item=><div key={item.id} className="px-4 py-3.5 sm:px-5"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-black">{item.customer_name||"Customer viewing"}</div><div className="mt-1 text-xs opacity-55">{item.listing_title||item.appointment_type} · {new Date(item.starts_at).toLocaleTimeString("en-ZA",{hour:"2-digit",minute:"2-digit"})}</div></div><span className="text-[10px] font-black uppercase opacity-45">Viewing</span></div></div>)}{[...overdue,...highLeads.filter(l=>!overdue.some(o=>o.id===l.id)),...leads].filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i).slice(0,5).map(lead=><button key={lead.id} type="button" onClick={()=>setSection("leads")} className="w-full px-4 py-3.5 text-left sm:px-5"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-black">{lead.customer_name||"Customer follow-up"}</div><div className="mt-1 text-xs opacity-55">{lead.listing_title||lead.source}{lead.priority==="high"?" · high activity":""}</div></div><span className="text-xs font-black opacity-45">{relativeAge(lead.last_activity_at||lead.created_at)}</span></div></button>)}</div>:<EmptyState title="Your day is clear" detail="New leads, follow-ups and appointments will appear here."/>}</Surface></div>
    <Surface darkMode={darkMode} className="overflow-hidden"><div className="border-b border-current/10 px-4 py-4 sm:px-5"><SectionHeading title="Dealership health" detail="Operational areas only — no artificial score."/></div><div className="grid sm:grid-cols-2 xl:grid-cols-3">{health.map(item=><button key={item.label} type="button" onClick={()=>setSection(item.section)} className="border-b border-current/10 p-4 text-left sm:border-r"><div className="text-[10px] font-black uppercase tracking-[.09em] opacity-40">{item.label}</div><div className="mt-2 text-sm font-black capitalize">{item.detail}</div></button>)}</div></Surface>
    <div className="grid gap-4 md:grid-cols-4"><Small darkMode={darkMode} label="This week" value={week.totals.vehicle_views.toLocaleString()} detail="vehicle views"/><Small darkMode={darkMode} label="This week" value={week.totals.leads} detail="new leads"/><Small darkMode={darkMode} label="30 days" value={summary.sold_30d} detail="vehicles marked sold"/><Small darkMode={darkMode} label="Audience" value={summary.followers.toLocaleString()} detail="dealership followers"/></div>
  </div>
}
function Small({darkMode,label,value,detail}:{darkMode:boolean;label:string;value:string|number;detail:string}){return <Surface darkMode={darkMode} className="p-4"><div className="text-[10px] font-black uppercase tracking-[.1em] opacity-40">{label}</div><div className="mt-2 text-3xl font-black tracking-[-.04em]">{value}</div><div className="mt-1 text-sm opacity-55">{detail}</div></Surface>}
