"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import LoadLinkSiteHeader from "@/components/LoadLinkSiteHeader";
import { supabase } from "@/lib/supabaseClient";
import { useLoadLinkTheme } from "@/lib/useLoadLinkTheme";

const PAGE_SIZE = 24;

type Dealer = {
  id:string; slug:string; name:string; profile_image_url?:string|null; cover_image_url?:string|null;
  short_bio?:string|null; business_description?:string|null; physical_location?:string|null;
  contact_email?:string|null; phone_number?:string|null; whatsapp_number?:string|null; website_url?:string|null;
  trading_hours?:string|null; year_established?:number|null; follower_count?:number|null; active_listing_count?:number|null;
  average_response_minutes?:number|null; response_rate?:number|null;
};
type Listing={id:string;title:string;city?:string|null;rate?:string|null;price_amount?:number|null;photos?:string[]|null;stock_status?:string|null;vehicle_year?:number|null;brand?:string|null;model?:string|null;created_at?:string|null};
type Update={id:string;update_type:string;title:string;body:string;image_url?:string|null;listing_id?:string|null;published_at?:string|null;created_at:string};
type Review={id:string;rating:number;body?:string|null;dealer_response?:string|null;created_at:string};
type DayHours={closed?:boolean;open?:string;close?:string};
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"] as const;

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join("").toUpperCase()||"LL"}
function money(listing:Listing){if(listing.rate)return listing.rate;if(Number(listing.price_amount||0)>0)return new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(Number(listing.price_amount));return "POA"}
function parseHours(raw?:string|null):Record<string,DayHours>|null{if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
function hoursSummary(raw?:string|null){if(!raw)return "Hours not supplied";const parsed=parseHours(raw);if(!parsed)return raw;const mon=parsed.Monday;const same=days.slice(0,5).every(d=>JSON.stringify(parsed[d])===JSON.stringify(mon));const bits:string[]=[];if(mon)bits.push(same?(mon.closed?"Mon–Fri closed":`Mon–Fri ${mon.open}–${mon.close}`):(mon.closed?"Mon closed":`Mon ${mon.open}–${mon.close}`));const sat=parsed.Saturday;if(sat)bits.push(sat.closed?"Sat closed":`Sat ${sat.open}–${sat.close}`);const sun=parsed.Sunday;if(sun&&!sun.closed)bits.push(`Sun ${sun.open}–${sun.close}`);return bits.join(" · ")||"Hours available"}
function todayHours(raw?:string|null){const parsed=parseHours(raw);if(!parsed)return hoursSummary(raw);const day=days[(new Date().getDay()+6)%7];const value=parsed[day];if(!value)return hoursSummary(raw);return value.closed?`${day}: Closed`:`${day}: ${value.open}–${value.close}`}
function viewerKey(){if(typeof window==="undefined")return "server";const key="loadlink-dealer-showroom-viewer-v1";let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem(key,value)}return value}

export default function PublicDealershipExperience({slug}:{slug:string}){
  const {darkMode,toggleTheme}=useLoadLinkTheme();
  const [dealer,setDealer]=useState<Dealer|null>(null);const [listings,setListings]=useState<Listing[]>([]);const [updates,setUpdates]=useState<Update[]>([]);const [reviews,setReviews]=useState<Review[]>([]);
  const [loading,setLoading]=useState(true);const [stockLoading,setStockLoading]=useState(false);const [following,setFollowing]=useState(false);const [query,setQuery]=useState("");const [stock,setStock]=useState("all");
  const [reviewOpen,setReviewOpen]=useState(false);const [reviewRating,setReviewRating]=useState(5);const [reviewBody,setReviewBody]=useState("");const [reviewNotice,setReviewNotice]=useState("");const [reviewSubmitting,setReviewSubmitting]=useState(false);

  useEffect(()=>{void loadDealer()},[slug]);
  useEffect(()=>{if(!dealer)return;const timer=window.setTimeout(()=>void loadStock(dealer.id),250);return()=>window.clearTimeout(timer)},[dealer?.id,query,stock]);

  const reviewAverage=useMemo(()=>reviews.length?reviews.reduce((sum,r)=>sum+Number(r.rating||0),0)/reviews.length:null,[reviews]);
  const bg=darkMode?"bg-black text-white":"bg-white text-black";const surface=darkMode?"border-white/10 bg-[#0b0b0b]":"border-black/10 bg-white";const muted=darkMode?"text-white/52":"text-black/52";

  async function loadDealer(){
    setLoading(true);const profile=await supabase.from("public_dealership_profiles").select("*").eq("slug",slug).maybeSingle();
    if(!profile.data){const redirect=await supabase.from("public_dealership_slug_redirects").select("current_slug").eq("old_slug",slug).maybeSingle();if(redirect.data?.current_slug){window.location.replace(`/dealership/${redirect.data.current_slug}`);return}setDealer(null);setLoading(false);return}
    const loaded=profile.data as Dealer;setDealer(loaded);
    const [updatesResult,reviewsResult,auth]=await Promise.all([supabase.from("public_dealership_updates").select("*").eq("dealership_id",loaded.id).order("published_at",{ascending:false}).limit(8),supabase.rpc("loadlink_public_dealer_reviews",{p_dealership_id:loaded.id,p_limit:30}),supabase.auth.getUser()]);
    setUpdates((updatesResult.data||[]) as Update[]);setReviews((reviewsResult.data||[]) as Review[]);
    void supabase.rpc("loadlink_record_dealer_profile_view",{p_dealership_id:loaded.id,p_viewer_key:viewerKey(),p_source:"showroom"});
    if(auth.data.user){const f=await supabase.from("dealership_followers").select("dealership_id").eq("dealership_id",loaded.id).eq("user_id",auth.data.user.id).maybeSingle();setFollowing(Boolean(f.data))}else setFollowing(false);
    await loadStock(loaded.id);setLoading(false);
  }

  async function loadStock(id=dealer?.id){if(!id)return;setStockLoading(true);const result=await supabase.rpc("loadlink_public_dealer_inventory",{p_dealership_id:id,p_page:1,p_page_size:PAGE_SIZE,p_query:query.trim(),p_stock:stock});const payload=(result.data||{items:[]}) as {items:Listing[]};setListings(payload.items||[]);setStockLoading(false)}
  async function toggleFollow(){if(!dealer)return;const auth=await supabase.auth.getUser();const user=auth.data.user;if(!user){window.location.assign(`/login?returnTo=${encodeURIComponent(`/dealership/${dealer.slug}`)}`);return}if(following){const r=await supabase.from("dealership_followers").delete().eq("dealership_id",dealer.id).eq("user_id",user.id);if(!r.error){setFollowing(false);setDealer(d=>d?{...d,follower_count:Math.max(0,Number(d.follower_count||0)-1)}:d)}}else{const r=await supabase.from("dealership_followers").insert({dealership_id:dealer.id,user_id:user.id});if(!r.error){setFollowing(true);setDealer(d=>d?{...d,follower_count:Number(d.follower_count||0)+1}:d)}}}
  async function submitReview(event:FormEvent){event.preventDefault();if(!dealer||reviewSubmitting)return;setReviewNotice("");const auth=await supabase.auth.getUser();if(!auth.data.user){window.location.assign(`/login?returnTo=${encodeURIComponent(`/dealership/${dealer.slug}#reviews`)}`);return}if(reviewBody.trim().length<5){setReviewNotice("Write at least 5 characters about your experience.");return}setReviewSubmitting(true);const result=await supabase.rpc("loadlink_submit_public_dealer_review",{p_dealership_id:dealer.id,p_rating:reviewRating,p_body:reviewBody.trim()});setReviewSubmitting(false);if(result.error){setReviewNotice(result.error.message||"Review could not be submitted.");return}const refresh=await supabase.rpc("loadlink_public_dealer_reviews",{p_dealership_id:dealer.id,p_limit:30});if(!refresh.error)setReviews((refresh.data||[]) as Review[]);setReviewBody("");setReviewNotice("Review published.");setReviewOpen(false)}

  if(loading)return <main className={`min-h-screen ${bg}`}><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/><div className="flex min-h-[70vh] items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-2 border-current/10 border-t-[#f6b800]"/></div></main>;
  if(!dealer)return <main className={`min-h-screen ${bg}`}><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/><div className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="text-3xl font-black">Showroom unavailable</h1><p className={`mt-3 text-sm font-semibold ${muted}`}>This dealership has not published its showroom yet.</p><Link href="/jobs" className="mt-6 inline-flex rounded-full border border-current/12 px-5 py-3 text-sm font-black">Back to marketplace</Link></div></main>;

  const whatsapp=(dealer.whatsapp_number||dealer.phone_number||"").replace(/\D/g,"");
  return <main className={`min-h-screen ${bg}`}><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/>
    <div className="mx-auto max-w-7xl px-3 pb-20 pt-3 sm:px-5 md:pt-6">
      <section className="relative min-h-[360px] overflow-hidden rounded-[30px] bg-[#080808] text-white md:min-h-[430px]">
        {dealer.cover_image_url?<img src={dealer.cover_image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-65"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/10"/>
        <div className="relative flex min-h-[360px] flex-col justify-end p-5 md:min-h-[430px] md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="flex min-w-0 items-end gap-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-full border-2 border-white/40 bg-black text-sm font-black text-[#f6b800] md:h-28 md:w-28">{dealer.profile_image_url?<img src={dealer.profile_image_url} alt={`${dealer.name} profile`} className="h-full w-full object-cover"/>:initials(dealer.name)}</div><div className="min-w-0 pb-1"><div className="text-[10px] font-black uppercase tracking-[.08em] text-white/55">Verified dealership{dealer.physical_location?` · ${dealer.physical_location}`:""}</div><h1 className="mt-2 text-3xl font-black tracking-[-.045em] sm:text-4xl md:text-5xl">{dealer.name}</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-white/68">{dealer.short_bio||dealer.business_description||"Commercial vehicle dealership on LoadLink."}</p><p className="mt-2 text-[11px] font-bold text-white/48">{todayHours(dealer.trading_hours)}</p></div></div>
          <div className="flex gap-2 overflow-x-auto"><button type="button" onClick={()=>void toggleFollow()} className={`h-11 shrink-0 rounded-full px-5 text-xs font-black ${following?"border border-white/20 bg-white/10 text-white":"bg-[#f6b800] text-black"}`}>{following?"Following":"Follow"}</button><a href="#showroom" className="flex h-11 shrink-0 items-center rounded-full border border-white/20 bg-black/45 px-5 text-xs font-black">Showroom</a><a href={`/messages?dealer=${encodeURIComponent(dealer.id)}`} className="flex h-11 shrink-0 items-center rounded-full border border-white/20 bg-black/45 px-5 text-xs font-black">Message</a>{dealer.phone_number?<a href={`tel:${dealer.phone_number}`} className="flex h-11 shrink-0 items-center rounded-full border border-white/20 bg-black/45 px-5 text-xs font-black">Call</a>:null}{whatsapp?<a href={`https://wa.me/${whatsapp}`} className="flex h-11 shrink-0 items-center rounded-full border border-white/20 bg-black/45 px-5 text-xs font-black">WhatsApp</a>:null}</div></div></div>
      </section>

      <section className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4"><Info title="Opening hours" value={hoursSummary(dealer.trading_hours)} darkMode={darkMode}/><Info title="Reviews" value={reviewAverage===null?"No reviews yet":`${reviewAverage.toFixed(1)} / 5 · ${reviews.length}`} darkMode={darkMode}/><Info title="Showroom" value={`${listings.length||Number(dealer.active_listing_count||0)} vehicles`} darkMode={darkMode}/><Info title="Followers" value={String(dealer.follower_count||0)} darkMode={darkMode}/></section>

      {updates.length?<section className="mt-8"><div className="mb-3 flex items-end justify-between"><div><h2 className="text-2xl font-black tracking-[-.03em]">Updates</h2><p className={`mt-1 text-xs font-semibold ${muted}`}>Latest from {dealer.name}</p></div></div><div className="no-scrollbar flex gap-3 overflow-x-auto pb-2">{updates.map(update=><article key={update.id} className={`w-[260px] shrink-0 overflow-hidden rounded-[22px] border ${surface}`}>{update.image_url?<img src={update.image_url} alt="" className="aspect-[4/3] w-full object-cover"/>:null}<div className="p-4"><h3 className="line-clamp-2 text-sm font-black">{update.title}</h3><p className={`mt-2 line-clamp-3 text-xs font-semibold leading-5 ${muted}`}>{update.body}</p></div></article>)}</div></section>:null}

      <section id="showroom" className="scroll-mt-28 pt-10"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 className="text-3xl font-black tracking-[-.04em]">Showroom</h2><p className={`mt-1 text-sm font-semibold ${muted}`}>Browse current stock from {dealer.name}.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search showroom" className={`h-11 min-w-0 rounded-full border px-4 text-sm font-semibold outline-none ${darkMode?"border-white/12 bg-white/[.04]":"border-black/10 bg-white"}`}/><select value={stock} onChange={e=>setStock(e.target.value)} className={`h-11 rounded-full border px-4 text-xs font-black outline-none ${darkMode?"border-white/12 bg-[#111]":"border-black/10 bg-white"}`}><option value="all">All stock</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option></select></div></div>
        {stockLoading?<div className="grid grid-cols-3 gap-1 pt-5 sm:gap-2">{Array.from({length:6}).map((_,i)=><div key={i} className={`aspect-square animate-pulse ${darkMode?"bg-white/[.06]":"bg-black/[.05]"}`}/>)}</div>:listings.length?<div className="grid grid-cols-3 gap-1 pt-5 sm:gap-2">{listings.map(item=><Link key={item.id} href={`/vehicles/${item.id}`} className="group relative aspect-square overflow-hidden bg-[#111]">{item.photos?.[0]?<img src={item.photos[0]} alt={item.title} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]"/>:<div className="flex h-full items-center justify-center text-xs font-black text-white/35">No photo</div>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-2 pt-10 text-white sm:p-3"><div className="truncate text-[10px] font-black sm:text-xs">{item.vehicle_year?`${item.vehicle_year} `:""}{item.brand||item.title} {item.model||""}</div><div className="mt-0.5 truncate text-[9px] font-bold text-white/65 sm:text-[10px]">{money(item)}</div></div></Link>)}</div>:<div className={`mt-5 rounded-[22px] border p-8 text-center ${surface}`}><h3 className="text-lg font-black">No vehicles in the showroom yet</h3><p className={`mt-2 text-sm font-semibold ${muted}`}>When this dealership publishes stock, it will appear here.</p></div>}
      </section>

      <section id="reviews" className="scroll-mt-28 pt-12"><div className="flex items-end justify-between gap-4"><div><h2 className="text-3xl font-black tracking-[-.04em]">Customer reviews</h2><p className={`mt-1 text-sm font-semibold ${muted}`}>{reviewAverage===null?"No reviews yet":`${reviewAverage.toFixed(1)} out of 5 from ${reviews.length} review${reviews.length===1?"":"s"}`}</p></div><button type="button" onClick={()=>setReviewOpen(true)} className="shrink-0 rounded-full bg-[#f6b800] px-5 py-3 text-xs font-black text-black">Write a review</button></div>
        {reviews.length?<div className="mt-5 grid gap-3 md:grid-cols-2">{reviews.map(review=><article key={review.id} className={`rounded-[22px] border p-5 ${surface}`}><div className="text-sm font-black">{"★".repeat(Math.max(1,Math.min(5,Number(review.rating))))}</div><p className={`mt-3 text-sm font-semibold leading-6 ${muted}`}>{review.body||"Rating submitted."}</p>{review.dealer_response?<div className={`mt-4 rounded-[16px] p-4 text-xs font-semibold leading-5 ${darkMode?"bg-white/[.05]":"bg-black/[.035]"}`}><strong className="block mb-1">Dealership response</strong>{review.dealer_response}</div>:null}</article>)}</div>:null}
      </section>

      {dealer.business_description?<section className={`mt-12 rounded-[26px] border p-6 ${surface}`}><h2 className="text-xl font-black">About {dealer.name}</h2><p className={`mt-3 max-w-4xl text-sm font-semibold leading-7 ${muted}`}>{dealer.business_description}</p></section>:null}
    </div>

    {reviewOpen?<div className="fixed inset-0 z-[2147483000] flex items-end bg-black/70 p-3 sm:items-center sm:justify-center" onClick={e=>{if(e.target===e.currentTarget)setReviewOpen(false)}}><form onSubmit={submitReview} className={`w-full max-w-md rounded-[26px] border p-5 shadow-2xl ${darkMode?"border-white/12 bg-[#0b0b0b] text-white":"border-black/10 bg-white text-black"}`}><div className="flex items-center justify-between"><h3 className="text-xl font-black">Review {dealer.name}</h3><button type="button" onClick={()=>setReviewOpen(false)} className="h-10 w-10 rounded-full border border-current/12 text-xl">×</button></div><label className="mt-5 block text-xs font-black">Rating<select value={reviewRating} onChange={e=>setReviewRating(Number(e.target.value))} className={`mt-2 h-11 w-full rounded-xl border px-3 ${darkMode?"border-white/10 bg-[#111]":"border-black/10 bg-white"}`}><option value={5}>5 — Excellent</option><option value={4}>4 — Good</option><option value={3}>3 — Average</option><option value={2}>2 — Poor</option><option value={1}>1 — Very poor</option></select></label><label className="mt-4 block text-xs font-black">Your experience<textarea value={reviewBody} onChange={e=>setReviewBody(e.target.value)} className={`mt-2 min-h-28 w-full rounded-xl border p-3 text-sm outline-none ${darkMode?"border-white/10 bg-white/[.04]":"border-black/10 bg-white"}`}/></label>{reviewNotice?<p className="mt-3 text-xs font-bold">{reviewNotice}</p>:null}<button disabled={reviewSubmitting} className="mt-5 min-h-12 w-full rounded-xl bg-[#f6b800] text-sm font-black text-black">{reviewSubmitting?"Publishing…":"Publish review"}</button></form></div>:null}
  </main>;
}

function Info({title,value,darkMode}:{title:string;value:string;darkMode:boolean}){return <div className={`min-h-[92px] rounded-[20px] border p-4 ${darkMode?"border-white/10 bg-white/[.035]":"border-black/10 bg-white"}`}><div className="text-[9px] font-black uppercase tracking-[.08em] opacity-42">{title}</div><div className="mt-2 line-clamp-2 text-xs font-black leading-5">{value}</div></div>}
