"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import LoadLinkSiteHeader from "@/components/LoadLinkSiteHeader";
import { supabase } from "@/lib/supabaseClient";
import { useLoadLinkTheme } from "@/lib/useLoadLinkTheme";

type Dealer = { id:string; slug:string; name:string; profile_image_url?:string|null; cover_image_url?:string|null; short_bio?:string|null; business_description?:string|null; physical_location?:string|null; phone_number?:string|null; whatsapp_number?:string|null; trading_hours?:string|null; follower_count?:number|null; active_listing_count?:number|null };
type Listing = { id:string; title:string; city?:string|null; rate?:string|null; price_amount?:number|null; photos?:string[]|null; stock_status?:string|null; vehicle_year?:number|null; brand?:string|null; model?:string|null };
type Review = { id:string; rating:number; body?:string|null };
type Update = { id:string; title:string; body:string; image_url?:string|null };

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()||"LL"}
function price(item:Listing){if(item.rate)return item.rate;if(Number(item.price_amount||0)>0)return new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(Number(item.price_amount));return "POA"}
function viewerKey(){if(typeof window==="undefined")return "server";const key="loadlink-dealer-showroom-viewer-v1";let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem(key,value)}return value}
function imageFallback(event:React.SyntheticEvent<HTMLImageElement>){const image=event.currentTarget;if(image.dataset.fallbackApplied==="true")return;image.dataset.fallbackApplied="true";image.src="/images/truck-1.jpg"}
function todayHours(raw?:string|null){if(!raw)return "Hours not supplied";try{const data=JSON.parse(raw) as Record<string,{closed?:boolean;open?:string;close?:string}>;const day=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][new Date().getDay()];const value=data[day];if(!value)return "Hours available";return value.closed?`${day}: Closed`:`${day}: ${value.open||"–"}–${value.close||"–"}`}catch{return raw}}

export default function PublicDealershipExperienceV2({slug}:{slug:string}){
  const {darkMode,toggleTheme}=useLoadLinkTheme();
  const [dealer,setDealer]=useState<Dealer|null>(null);const [listings,setListings]=useState<Listing[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [updates,setUpdates]=useState<Update[]>([]);
  const [following,setFollowing]=useState(false);const [canEdit,setCanEdit]=useState(false);const [query,setQuery]=useState("");const [stock,setStock]=useState("all");const [loading,setLoading]=useState(true);const [stockLoading,setStockLoading]=useState(false);
  const page=darkMode?"bg-black text-white":"bg-[#f5f1e8] text-black";const muted=darkMode?"text-white/52":"text-black/54";const border=darkMode?"border-white/10":"border-black/10";
  const average=useMemo(()=>reviews.length?reviews.reduce((sum,item)=>sum+Number(item.rating||0),0)/reviews.length:null,[reviews]);

  useEffect(()=>{let alive=true;async function load(){setLoading(true);const profile=await supabase.from("public_dealership_profiles").select("*").eq("slug",slug).maybeSingle();if(!alive)return;if(!profile.data){const moved=await supabase.from("public_dealership_slug_redirects").select("current_slug").eq("old_slug",slug).maybeSingle();if(moved.data?.current_slug)window.location.replace(`/dealership/${moved.data.current_slug}`);else{setDealer(null);setLoading(false)}return}const current=profile.data as Dealer;setDealer(current);const [inventory,reviewResult,updateResult,auth]=await Promise.all([supabase.rpc("loadlink_public_dealer_inventory",{p_dealership_id:current.id,p_page:1,p_page_size:48,p_query:"",p_stock:"all"}),supabase.rpc("loadlink_public_dealer_reviews",{p_dealership_id:current.id,p_limit:12}),supabase.from("public_dealership_updates").select("id,title,body,image_url").eq("dealership_id",current.id).order("published_at",{ascending:false}).limit(4),supabase.auth.getUser()]);if(!alive)return;setListings(((inventory.data||{items:[]}) as {items?:Listing[]}).items||[]);setReviews((reviewResult.data||[]) as Review[]);setUpdates((updateResult.data||[]) as Update[]);const user=auth.data.user;if(user){const [follow,owner,staff]=await Promise.all([supabase.from("dealership_followers").select("dealership_id").eq("dealership_id",current.id).eq("user_id",user.id).maybeSingle(),supabase.from("dealership_profiles").select("id").eq("id",current.id).eq("owner_user_id",user.id).maybeSingle(),supabase.from("dealership_staff").select("dealership_id").eq("dealership_id",current.id).eq("user_id",user.id).limit(1).maybeSingle()]);if(!alive)return;setFollowing(Boolean(follow.data));setCanEdit(Boolean(owner.data||staff.data))}void supabase.rpc("loadlink_record_dealer_profile_view",{p_dealership_id:current.id,p_viewer_key:viewerKey(),p_source:"showroom"});setLoading(false)}void load();return()=>{alive=false}},[slug]);

  useEffect(()=>{if(!dealer)return;const timer=window.setTimeout(async()=>{setStockLoading(true);const result=await supabase.rpc("loadlink_public_dealer_inventory",{p_dealership_id:dealer.id,p_page:1,p_page_size:48,p_query:query.trim(),p_stock:stock});setListings(((result.data||{items:[]}) as {items?:Listing[]}).items||[]);setStockLoading(false)},220);return()=>window.clearTimeout(timer)},[dealer?.id,query,stock]);

  async function toggleFollow(){if(!dealer)return;const auth=await supabase.auth.getUser();if(!auth.data.user){window.location.assign(`/login?returnTo=${encodeURIComponent(`/dealership/${dealer.slug}`)}`);return}if(following){const result=await supabase.from("dealership_followers").delete().eq("dealership_id",dealer.id).eq("user_id",auth.data.user.id);if(!result.error)setFollowing(false)}else{const result=await supabase.from("dealership_followers").insert({dealership_id:dealer.id,user_id:auth.data.user.id});if(!result.error)setFollowing(true)}}

  if(loading)return <main className={`min-h-screen ${page}`}><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/><div className="grid min-h-[70vh] place-items-center"><div className="h-9 w-9 animate-spin rounded-full border-2 border-current/15 border-t-[#f6b800]"/></div></main>;
  if(!dealer)return <main className={`min-h-screen ${page}`}><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/><section className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="text-3xl font-black">Showroom unavailable</h1><p className={`mt-3 text-sm font-semibold ${muted}`}>This dealership has not published a showroom.</p><Link href="/" className="mt-6 inline-flex rounded-full border border-current/15 px-5 py-3 text-sm font-black">Back to LoadLink</Link></section></main>;

  const whatsapp=String(dealer.whatsapp_number||dealer.phone_number||"").replace(/\D/g,"");const count=listings.length||Number(dealer.active_listing_count||0);
  return <main className={`min-h-screen ${page}`} data-loadlink-public-showroom="source-v2"><LoadLinkSiteHeader darkMode={darkMode} onToggleTheme={toggleTheme}/><div className="mx-auto max-w-7xl px-4 pb-20 pt-4 sm:px-6 md:pt-7">
    <section className="relative overflow-hidden rounded-[26px] bg-[#080808] text-white"><div className="relative min-h-[370px] md:min-h-[420px]">{dealer.cover_image_url?<img src={dealer.cover_image_url} alt="" className="absolute inset-0 h-full w-full object-cover object-center opacity-62"/>:<img src="/images/jobs/jobs-hero-fleet.jpg" alt="" className="absolute inset-0 h-full w-full object-cover object-center opacity-46"/>}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/52 to-black/10"/>{canEdit?<Link href="/dealer?section=showroom" className="absolute right-4 top-4 z-20 inline-flex h-10 items-center gap-2 rounded-full border border-white/20 bg-black/60 px-4 text-[11px] font-black text-white backdrop-blur-xl" aria-label="Edit showroom"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m5 19 1-4 9.8-9.8a2.1 2.1 0 0 1 3 3L9 18l-4 1Z" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"/></svg>Edit showroom</Link>:null}<div className="absolute inset-x-0 bottom-0 z-10 p-5 sm:p-7 md:p-9"><div className="flex items-end gap-4"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-full border border-white/30 bg-black font-black text-[#f6b800] sm:h-24 sm:w-24">{dealer.profile_image_url?<img src={dealer.profile_image_url} alt={`${dealer.name} profile`} className="h-full w-full object-cover"/>:initials(dealer.name)}</div><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.12em] text-white/50">Verified dealership</p><h1 className="mt-1 truncate text-3xl font-black tracking-[-.05em] sm:text-4xl md:text-5xl">{dealer.name}</h1>{dealer.physical_location?<p className="mt-1 text-xs font-semibold text-white/58">{dealer.physical_location}</p>:null}</div></div><p className="mt-4 max-w-2xl text-sm font-semibold leading-6 text-white/68">{dealer.short_bio||dealer.business_description||"Commercial vehicle dealership on LoadLink."}</p><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={()=>void toggleFollow()} className={`h-10 rounded-full px-4 text-[11px] font-black ${following?"border border-white/18 bg-white/10 text-white":"bg-[#f6b800] text-black"}`}>{following?"Following":"Follow"}</button><Link href={`/messages?dealer=${encodeURIComponent(dealer.id)}`} className="flex h-10 items-center rounded-full border border-white/18 bg-black/42 px-4 text-[11px] font-black">Message</Link>{dealer.phone_number?<a href={`tel:${dealer.phone_number}`} className="flex h-10 items-center rounded-full border border-white/18 bg-black/42 px-4 text-[11px] font-black">Call</a>:null}{whatsapp?<a href={`https://wa.me/${whatsapp}`} className="flex h-10 items-center rounded-full border border-white/18 bg-black/42 px-4 text-[11px] font-black">WhatsApp</a>:null}</div></div></div></section>
    <div className={`mt-4 flex flex-wrap gap-x-6 gap-y-2 border-b pb-4 text-xs font-bold ${border} ${muted}`}><span><b className={darkMode?"text-white":"text-black"}>{count}</b> in showroom</span><span><b className={darkMode?"text-white":"text-black"}>{average===null?"—":average.toFixed(1)}</b> rating</span><span><b className={darkMode?"text-white":"text-black"}>{dealer.follower_count||0}</b> followers</span><span>{todayHours(dealer.trading_hours)}</span></div>
    {updates.length?<section className="pt-8"><h2 className="text-2xl font-black tracking-[-.04em]">Latest updates</h2><div className="no-scrollbar mt-4 flex gap-3 overflow-x-auto pb-2">{updates.map((item)=><article key={item.id} className={`w-[250px] shrink-0 overflow-hidden rounded-[18px] border ${border} ${darkMode?"bg-white/[.035]":"bg-white"}`}>{item.image_url?<img src={item.image_url} alt="" onError={imageFallback} className="aspect-[16/9] w-full object-cover"/>:null}<div className="p-4"><h3 className="line-clamp-1 text-sm font-black">{item.title}</h3><p className={`mt-1 line-clamp-2 text-xs font-semibold leading-5 ${muted}`}>{item.body}</p></div></article>)}</div></section>:null}
    <section id="showroom" className="scroll-mt-24 pt-10"><div className={`flex flex-col gap-4 border-b pb-5 md:flex-row md:items-end md:justify-between ${border}`}><div><h2 className="text-3xl font-black tracking-[-.05em]">Showroom</h2><p className={`mt-1 text-sm font-semibold ${muted}`}>Current stock from {dealer.name}.</p></div><div className="grid gap-2 sm:grid-cols-[minmax(220px,1fr)_auto]"><input value={query} onChange={(event)=>setQuery(event.target.value)} inputMode="search" placeholder="Search make, model or vehicle" className={`h-11 rounded-xl border px-4 text-sm font-semibold outline-none focus:border-[#f6b800] ${darkMode?"border-white/12 bg-white/[.045] text-white placeholder:text-white/30":"border-black/10 bg-white text-black placeholder:text-black/35"}`}/><select value={stock} onChange={(event)=>setStock(event.target.value)} className={`h-11 rounded-xl border px-3 text-xs font-black outline-none ${darkMode?"border-white/12 bg-[#111] text-white":"border-black/10 bg-white text-black"}`}><option value="all">All stock</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option></select></div></div>{stockLoading?<div className="grid gap-3 pt-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,index)=><div key={index} className={`h-[300px] animate-pulse rounded-[18px] ${darkMode?"bg-white/[.05]":"bg-black/[.05]"}`}/>)}</div>:listings.length?<div className="grid gap-3 pt-5 sm:grid-cols-2 lg:grid-cols-3">{listings.map((item)=><Link key={item.id} href={`/vehicles/${item.id}`} className={`group overflow-hidden rounded-[18px] border ${border} ${darkMode?"bg-[#090909]":"bg-white"}`}><div className="relative aspect-[16/10] overflow-hidden bg-[#111]"><img src={item.photos?.[0]||"/images/truck-1.jpg"} onError={imageFallback} alt={item.title||"Commercial vehicle"} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]"/>{item.stock_status?<span className="absolute left-3 top-3 rounded-full bg-black/66 px-2.5 py-1 text-[9px] font-black uppercase text-white">{item.stock_status}</span>:null}</div><div className="p-4"><p className="truncate text-base font-black">{item.title||[item.vehicle_year,item.brand,item.model].filter(Boolean).join(" ")||"Commercial vehicle"}</p><div className="mt-2 flex items-center justify-between gap-3"><span className={`truncate text-xs font-semibold ${muted}`}>{item.city||"South Africa"}</span><span className="shrink-0 text-sm font-black text-[#a87900]">{price(item)}</span></div></div></Link>)}</div>:<div className={`mt-5 rounded-[18px] border p-8 text-center ${border}`}><h3 className="text-lg font-black">No matching stock</h3><p className={`mt-2 text-sm font-semibold ${muted}`}>Try a broader search or choose all stock.</p></div>}</section>
    <section className={`mt-12 border-t pt-8 ${border}`}><h2 className="text-2xl font-black tracking-[-.04em]">Customer reviews</h2>{reviews.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{reviews.slice(0,6).map((review)=><article key={review.id} className={`rounded-[18px] border p-4 ${border} ${darkMode?"bg-white/[.025]":"bg-white"}`}><p className="text-sm font-black">{"★".repeat(Math.max(1,Math.min(5,Number(review.rating||0))))}</p>{review.body?<p className={`mt-2 text-sm font-semibold leading-6 ${muted}`}>{review.body}</p>:null}</article>)}</div>:<p className={`mt-2 text-sm font-semibold ${muted}`}>No reviews yet.</p>}</section>
  </div></main>
}
