"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { dealerFetch, formatZar } from "@/lib/dealer/client";

type QuoteView = { quote_number: string; status: string; created_at: string; expires_at?: string | null; dealership_name: string; dealership_logo?: string | null; customer_name?: string | null; vehicle_title?: string | null; vehicle_price: number; fees_amount: number; extras_amount: number; trade_in_amount: number; total_amount: number; notes?: string | null; sales_name?: string | null };
export default function DealerQuotePage() {
  const params = useParams<{ id: string }>(); const [q, setQ] = useState<QuoteView | null>(null);
  useEffect(() => { void dealerFetch<QuoteView>(`/api/dealer/quotes?quote_id=${params.id}`).then(setQ).catch(() => setQ(null)); }, [params.id]);
  if (!q) return <main className="min-h-screen bg-white p-8 text-black">Loading quote…</main>;
  const lines = [["Vehicle", q.vehicle_price], ["Fees", q.fees_amount], ["Extras", q.extras_amount], ["Trade-in allowance", -q.trade_in_amount]] as const;
  return <main className="min-h-screen bg-white text-black"><div className="mx-auto max-w-3xl p-6 sm:p-10"><div className="flex items-start justify-between gap-4 border-b border-black/10 pb-5"><div className="flex items-center gap-3">{q.dealership_logo ? <img src={q.dealership_logo} alt="" className="h-12 w-12 rounded-full object-cover" /> : null}<div><div className="text-lg font-black">{q.dealership_name}</div><div className="text-xs text-black/50">LoadLink Dealer quote</div></div></div><button type="button" className="print:hidden rounded-lg border border-black/10 px-4 py-2 text-sm font-black" onClick={() => window.print()}>Print / Save PDF</button></div><div className="mt-6 flex flex-wrap justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.12em] text-black/40">Quote</div><h1 className="mt-1 text-3xl font-black">{q.quote_number}</h1></div><div className="text-right text-sm"><div>{new Date(q.created_at).toLocaleDateString("en-ZA")}</div>{q.expires_at ? <div className="mt-1 text-black/50">Valid until {new Date(q.expires_at).toLocaleDateString("en-ZA")}</div> : null}</div></div><div className="mt-7 border border-black/10 p-5"><div className="text-sm"><b>Customer:</b> {q.customer_name || "Customer"}</div><div className="mt-2 text-sm"><b>Vehicle:</b> {q.vehicle_title || "Vehicle"}</div>{q.sales_name ? <div className="mt-2 text-sm"><b>Sales consultant:</b> {q.sales_name}</div> : null}</div><div className="mt-5 divide-y divide-black/10 border border-black/10">{lines.map(([label, amount]) => <div key={label} className="flex justify-between gap-4 px-4 py-3 text-sm"><span>{label}</span><b>{formatZar(amount)}</b></div>)}<div className="flex justify-between gap-4 px-4 py-4 text-lg"><b>Total</b><b>{formatZar(q.total_amount)}</b></div></div>{q.notes ? <div className="mt-6 text-sm"><b>Notes</b><p className="mt-2 whitespace-pre-wrap text-black/60">{q.notes}</p></div> : null}</div></main>;
}
