"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import AuthStatusButton from "@/components/AuthStatusButton";
import HomeLogoLink from "@/components/HomeLogoLink";
import LoadLinkPagination from "@/components/LoadLinkPagination";
import LoadLinkThemeToggle from "@/components/LoadLinkThemeToggle";
import SiteMenu from "@/components/SiteMenu";
import PublicDealerStatus from "@/components/dealer/PublicDealerStatus";
import { supabase } from "@/lib/supabaseClient";
import { useLoadLinkTheme } from "@/lib/useLoadLinkTheme";

const PAGE_SIZE = 8;
type Dealer = { id:string; slug:string; name:string; profile_image_url?:string|null; cover_image_url?:string|null; short_bio?:string|null; business_description?:string|null; physical_location?:string|null; contact_email?:string|null; phone_number?:string|null; whatsapp_number?:string|null; website_url?:string|null; trading_hours?:string|null; year_established?:number|null; follower_count?:number|null; active_listing_count?:number|null; average_response_minutes?:number|null; response_rate?:number|null };
type Listing = { id:string; title:string; city:string; rate:string; price_amount?:number|null; photos?:string[]|null; stock_status?:string|null; vehicle_year?:number|null; brand?:string|null; model?:string|null; created_at?:string|null };
type Update = { id:string; update_type:string; title:string; body:string; image_url?:string|null; listing_id?:string|null; published_at?:string|null; created_at:string };
type Review = { id:string; rating:number; body?:string|null; dealer_response?:string|null; dealer_response_at?:string|null; created_at:string };

export default function DealershipPage({ params }: { params: { slug: string } }) {
  const { darkMode, toggleTheme } = useLoadLinkTheme(); const [dealer, setDealer] = useState<Dealer | null>(null); const [listings, setListings] = useState<Listing[]>([]); const [updates, setUpdates] = useState<Update[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(true); const [stockLoading, setStockLoading] = useState(false); const [following, setFollowing] = useState(false); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [total, setTotal] = useState(0); const [query, setQuery] = useState(""); const [stock, setStock] = useState("all");
  const muted = darkMode ? "text-white/55" : "text-black/55"; const surface = darkMode ? "border-white/10 bg-[#0c0c0c] text-white" : "border-black/10 bg-white text-black";
  useEffect(() => { void loadDealer(); }, [params.slug]);
  useEffect(() => { if (!dealer) return; const t = setTimeout(()=>void loadStock(1),220); return ()=>clearTimeout(t); }, [dealer?.id, query, stock]);

  async function loadDealer() {
    setLoading(true); const profile = await supabase.from("public_dealership_profiles").select("*").eq("slug", params.slug).maybeSingle();
    if (!profile.data) { const redirect = await supabase.from("public_dealership_slug_redirects").select("current_slug").eq("old_slug",params.slug).maybeSingle(); if (redirect.data?.current_slug) { window.location.replace(`/dealership/${redirect.data.current_slug}`); return; } setDealer(null); setLoading(false); return; }
    const d = profile.data as Dealer; setDealer(d);
    const [updateResult, reviewResult, auth] = await Promise.all([supabase.from("public_dealership_updates").select("*").eq("dealership_id",d.id).order("published_at",{ascending:false}).limit(6),supabase.rpc("loadlink_public_dealer_reviews",{p_dealership_id:d.id,p_limit:6}),supabase.auth.getUser()]);
    setUpdates((updateResult.data || []) as Update[]); setReviews((reviewResult.data || []) as Review[]); void recordProfileView(d.id);
    if (auth.data.user) { const follower = await supabase.from("dealership_followers").select("dealership_id").eq("dealership_id",d.id).eq("user_id",auth.data.user.id).maybeSingle(); setFollowing(Boolean(follower.data)); }
    await loadStock(1,d.id); setLoading(false);
  }

  async function loadStock(nextPage=1, dealerId=dealer?.id) {
    if (!dealerId) return; setStockLoading(true);
    const result=await supabase.rpc("loadlink_public_dealer_inventory",{p_dealership_id:dealerId,p_page:nextPage,p_page_size:PAGE_SIZE,p_query:query.trim(),p_stock:stock});
    const payload=(result.data||{items:[],total:0,page:nextPage,pages:1}) as {items:Listing[];total:number;page:number;pages:number};
    setListings(payload.items||[]); setTotal(Number(payload.total||0)); setPages(Math.max(1,Number(payload.pages||1))); setPage(Number(payload.page||nextPage)); setStockLoading(false);
  }


  function viewerKey(){ if(typeof window==="undefined") return "server"; const k="loadlink-dealer-showroom-viewer-v1"; let v=window.localStorage.getItem(k); if(!v){v=typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;window.localStorage.setItem(k,v);} return v; }
  async function recordProfileView(dealerId:string){ try{ await supabase.rpc("loadlink_record_dealer_profile_view",{p_dealership_id:dealerId,p_viewer_key:viewerKey(),p_source:"showroom"}); }catch{} }

  async function toggleFollow() { if (!dealer) return; const { data:{user} }=await supabase.auth.getUser(); if(!user){window.location.assign(`/login?returnTo=${encodeURIComponent(`/dealership/${dealer.slug}`)}`);return;} if(following) await supabase.from("dealership_followers").delete().eq("dealership_id",dealer.id).eq("user_id",user.id); else await supabase.from("dealership_followers").insert({dealership_id:dealer.id,user_id:user.id}); setFollowing(!following); }
  function responseText() { if (!dealer?.average_response_minutes) return null; if(dealer.average_response_minutes<60) return `Usually responds in about ${Math.max(1,Math.round(dealer.average_response_minutes))} min`; return `Usually responds in about ${Math.max(1,Math.round(dealer.average_response_minutes/60))} hr`; }

  return <main className={darkMode ? "min-h-screen bg-black text-white" : "min-h-screen bg-[#f4efe3] text-black"}>
    <header className={`sticky top-0 z-50 border-b ${darkMode ? "border-white/10 bg-black/95" : "border-black/10 bg-white/95"}`}><div className="grid h-20 grid-cols-[92px_1fr_52px] items-center px-4 backdrop-blur-md"><div className="flex items-center gap-2"><SiteMenu darkMode={darkMode}/><AuthStatusButton darkMode={darkMode}/></div><HomeLogoLink theme={darkMode?"dark":"light"}/><LoadLinkThemeToggle darkMode={darkMode} onToggle={toggleTheme} className="ml-auto"/></div></header>
    {loading ? <div className="flex min-h-[70vh] items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-2 border-current/10 border-t-[#f6b800]"/></div> : !dealer ? <div className="mx-auto max-w-3xl px-4 py-20 text-center"><h1 className="text-3xl font-black">Dealership not available</h1><p className={`mt-3 ${muted}`}>This showroom is not public or could not be found.</p></div> : <section className="mx-auto max-w-7xl px-4 pb-16 pt-5 md:px-6 md:pt-8">
      <section className="relative min-h-[310px] overflow-hidden border border-white/10 bg-[#080808] text-white">{dealer.cover_image_url?<img src={dealer.cover_image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-50"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/65 to-black/20"/><div className="relative flex min-h-[310px] flex-col justify-end p-5 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="flex min-w-0 items-end gap-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden border border-white/20 bg-black">{dealer.profile_image_url?<img src={dealer.profile_image_url} alt={`${dealer.name} logo`} className="h-full w-full object-cover"/>:<span className="text-sm font-black">LL</span>}</div><div className="min-w-0 pb-1"><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] font-black uppercase tracking-[.08em] text-white/65"><span className="text-white">✓ Verified Dealer</span>{dealer.physical_location?<span>{dealer.physical_location}</span>:null}</div><h1 className="mt-2 text-3xl font-black tracking-[-.045em] sm:text-4xl md:text-5xl">{dealer.name}</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-white/65">{dealer.short_bio||"Commercial vehicle dealership on LoadLink."}</p>{responseText()?<p className="mt-2 text-xs font-bold text-white/50">{responseText()} {dealer.response_rate ? `· ${Math.round(Number(dealer.response_rate))}% response rate` : ""}</p>:null}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>void toggleFollow()} className={`h-11 px-5 text-xs font-black ${following?"border border-white/20 bg-white/10 text-white":"bg-[#f6b800] text-black"}`}>{following?"Following":"Follow"}</button>{dealer.phone_number?<a href={`tel:${dealer.phone_number}`} className="flex h-11 items-center border border-white/20 bg-black/45 px-5 text-xs font-black">Call</a>:null}{dealer.whatsapp_number?<a href={`https://wa.me/${dealer.whatsapp_number.replace(/\D/g,"")}`} className="flex h-11 items-center border border-white/20 bg-black/45 px-5 text-xs font-black">WhatsApp</a>:null}</div></div></div></section>

      <PublicDealerStatus dealerId={dealer.id} dealerSlug={dealer.slug} darkMode={darkMode} />

      {updates.length ? <section className={`mt-5 overflow-hidden border ${surface}`}><div className="border-b border-current/10 px-4 py-4 sm:px-5"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Dealership updates</h2><span className={`text-xs font-bold ${muted}`}>Latest</span></div></div><div className="grid divide-y divide-current/10 lg:grid-cols-3 lg:divide-x lg:divide-y-0">{updates.slice(0,3).map(u=><article key={u.id} className="p-4 sm:p-5">{u.image_url?<img src={u.image_url} alt="" className="mb-4 aspect-[16/8] w-full object-cover"/>:null}<div className={`text-[10px] font-black uppercase tracking-[.08em] ${muted}`}>{u.update_type.replaceAll("_"," ")}</div><h3 className="mt-2 text-base font-black">{u.title}</h3><p className={`mt-2 line-clamp-3 text-sm leading-6 ${muted}`}>{u.body}</p>{u.listing_id?<Link href={`/vehicles/${u.listing_id}`} className="mt-3 inline-block text-xs font-black underline underline-offset-4">View vehicle</Link>:null}</article>)}</div></section>:null}

      <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_320px]">
        <section className={`overflow-hidden border ${surface}`}><div className="border-b border-current/10 p-4 sm:p-5"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-2xl font-black">Vehicles</h2><p className={`mt-1 text-xs font-semibold ${muted}`}>{total} active vehicle{total===1?"":"s"}</p></div><div className="grid gap-2 sm:grid-cols-[260px_140px]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this dealership" className={`h-10 border px-3 text-sm font-semibold outline-none focus:border-[#f6b800] ${darkMode?"border-white/12 bg-[#111]":"border-black/10 bg-[#faf8f2]"}`}/><select value={stock} onChange={e=>setStock(e.target.value)} className={`h-10 border px-3 text-xs font-bold outline-none ${darkMode?"border-white/12 bg-[#111]":"border-black/10 bg-[#faf8f2]"}`}><option value="all">Available + reserved</option><option value="available">Available</option><option value="reserved">Reserved</option></select></div></div></div>{stockLoading?<div className="px-5 py-14 text-center text-sm font-bold opacity-45">Loading stock…</div>:listings.length?<div className="grid gap-4 p-4 sm:grid-cols-2 md:p-5">{listings.map(item=><Link key={item.id} href={`/vehicles/${item.id}`} className={`group overflow-hidden border transition hover:border-current/40 ${darkMode?"border-white/10 bg-white/[.02]":"border-black/8 bg-[#faf8f2]"}`}><div className="aspect-[16/10] overflow-hidden bg-black/[.05]">{item.photos?.[0]?<img src={item.photos[0]} alt={item.title} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.015]"/>:null}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="min-w-0 flex-1 font-black">{item.title}</h3>{item.stock_status==="reserved"?<span className="border border-current/15 px-2 py-1 text-[9px] font-black uppercase">Reserved</span>:null}</div><p className={`mt-2 text-xs font-semibold ${muted}`}>{[item.vehicle_year,item.brand,item.model,item.city].filter(Boolean).join(" · ")}</p><p className="mt-3 text-lg font-black">{item.rate}</p></div></Link>)}</div>:<div className="p-10 text-center"><p className="font-black">No matching stock</p><p className={`mt-2 text-xs font-semibold ${muted}`}>Try another search or follow the dealership for future arrivals.</p></div>}{pages>1?<div className="border-t border-current/10 p-4"><LoadLinkPagination current={page} total={pages} onChange={p=>void loadStock(p)} darkMode={darkMode} label="Dealership stock pages"/></div>:null}</section>
        <aside className="grid content-start gap-4"><section className={`border p-5 ${surface}`}><h2 className="text-lg font-black">Dealership details</h2><div className="mt-4 space-y-4 text-sm font-semibold"><Detail label="Location" value={dealer.physical_location} muted={muted}/><Detail label="Trading hours" value={dealer.trading_hours} muted={muted}/><Detail label="Established" value={dealer.year_established?String(dealer.year_established):null} muted={muted}/><Detail label="Active stock" value={String(dealer.active_listing_count||0)} muted={muted}/></div></section>{dealer.business_description?<section className={`border p-5 ${surface}`}><h2 className="text-lg font-black">About</h2><p className={`mt-3 text-sm font-semibold leading-6 ${muted}`}>{dealer.business_description}</p>{dealer.website_url?<a href={dealer.website_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs font-black underline underline-offset-4">Website</a>:null}</section>:null}</aside>
      </div>

      {reviews.length ? <section className={`mt-5 overflow-hidden border ${surface}`}><div className="border-b border-current/10 px-4 py-4 sm:px-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-black">Customer reviews</h2><p className={`mt-1 text-xs font-semibold ${muted}`}>Verified LoadLink interactions only.</p></div><div className="text-sm font-black">{(reviews.reduce((sum,r)=>sum+Number(r.rating||0),0)/reviews.length).toFixed(1)} / 5</div></div></div><div className="grid divide-y divide-current/10 md:grid-cols-2 md:divide-x md:divide-y-0">{reviews.slice(0,4).map(r=><article key={r.id} className="p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div className="text-sm font-black">{r.rating}/5</div><div className={`text-[11px] font-semibold ${muted}`}>{new Date(r.created_at).toLocaleDateString("en-ZA",{day:"numeric",month:"short",year:"numeric"})}</div></div>{r.body?<p className={`mt-3 text-sm leading-6 ${muted}`}>{r.body}</p>:null}{r.dealer_response?<div className="mt-4 border-l-2 border-current/15 pl-3"><div className="text-xs font-black">Dealer response</div><p className={`mt-1 text-sm leading-6 ${muted}`}>{r.dealer_response}</p></div>:null}</article>)}</div></section>:null}
    </section>}
  </main>;
}
function Detail({label,value,muted}:{label:string;value?:string|null;muted:string}){if(!value)return null;return <div><p className={`text-[9px] font-black uppercase tracking-[.08em] ${muted}`}>{label}</p><p className="mt-1 font-bold">{value}</p></div>}
